Removed excessive message print
digitalfabrik/integreat-cms pull request #1747
Opened 2022-10-11 16:41 UTC by seluianova

### Short description
Bug summary: when creating a user whose name already exists, the system displays the message "Pending account activation", which is incorrect.

### Proposed changes
Removed excessive message print 

### Side effects
Didn't find any.

### Resolved issues
Fixes: #1703

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2022-10-11 17:43 UTC, MizukiTemma commented
Congratulation for the first PR and thank you for your contribution 😄 
The error message is gone and it's nice that the change is applied also in the global user form.

Can you add an entry in CHANGELOG.md under UNRELEASED?

2022-10-11 17:44 UTC, MizukiTemma requested changes
Congratulation for the first PR and thank you for your contribution 😄
The error message is gone and it's nice that the change is applied also in the global user form.

Can you add an entry in CHANGELOG.md under UNRELEASED?

2022-10-11 21:42 UTC, timoludwig approved these changes
Thanks a lot and welcome to the team! :muscle: :rocket: 

Looks good and does exactly what it's supposed to, I just have an optional suggestion for the changelog :wink:

2022-10-11 21:42 UTC, timoludwig commented on CHANGELOG.md
> +* [ [#1703](https://github.com/digitalfabrik/integreat-cms/issues/1703) ] Removed excessive message print when creating a user whose name already exists
```suggestion
* [ [#1703](https://github.com/digitalfabrik/integreat-cms/issues/1703) ] Remove pending account activation warning when user form is submitted with errors
```
Sorry for being nitpicky here :grin: 
Two small ideas for improvement:
- I think we can be more precise about what has really been changed
- We try to use the [imperative mood](https://cbea.ms/git-commit/#imperative) for commit messages and changelog entries

2022-10-12 10:28 UTC, timoludwig requested changes
Thanks a lot, looks good now! :+1:
Could you squash your commits and rebase the branch onto develop as described [here](https://digitalfabrik.github.io/integreat-cms/git-flow.html#update-feature-branch) to clean up the git history a bit?

2022-10-12 10:40 UTC, timoludwig approved these changes
Thanks! :pray:

2022-10-12 11:48 UTC, MizukiTemma commented
@seluianova 
Thank you! It's ready to be merged 😃

2022-10-12 12:20 UTC, merged