Add adjusted error message for statistics page
digitalfabrik/integreat-cms pull request #1776
Opened 2022-10-18 07:04 UTC by SteffiStuffel

### Short description

Adjusted the error message. 

### Resolved issues

Fixes: #1700 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2022-10-18 09:10 UTC, timoludwig reviewed
Thanks a lot! :+1:

This is definitely an improvement, I was just wondering whether this is now misleading in the case that something else went wrong and it's not the Matomo timeout causing the error...
Do you think it is worth looking into the different possible exceptions the [MatomoApiManager](https://github.com/digitalfabrik/integreat-cms/blob/develop/integreat_cms/cms/utils/matomo_api_manager.py) can throw and then differentiating them [here](https://github.com/digitalfabrik/integreat-cms/blob/15ce171cc8041bac2d24823e271632db56eaebf1/integreat_cms/cms/views/statistics/statistics_actions.py#L94-L96) to show two different kind of server error messages in the frontend [here](https://github.com/digitalfabrik/integreat-cms/blob/15ce171cc8041bac2d24823e271632db56eaebf1/integreat_cms/cms/templates/statistics/statistics_overview.html#L19)?
Not sure whether it's worth the effort though.

2022-10-19 08:54 UTC, timoludwig commented
@SteffiStuffel sorry for misleading you, I just noticed that the MatomoApiManager does in fact not handle timeout errors gracefully since the exception thrown is an `asyncio.TimeoutError` which is no subclass of `aiohttp.ClientError`.
This means we could e.g. handle the error directly in the view with:
```
    except asyncio.TimeoutError:
        return JsonResponse(
            {"error": "Timeout during request to Matomo API"}, status=504
        )
```
in the views [here](https://github.com/digitalfabrik/integreat-cms/blob/15ce171cc8041bac2d24823e271632db56eaebf1/integreat_cms/cms/views/statistics/statistics_actions.py#L47-L51) and [here](https://github.com/digitalfabrik/integreat-cms/blob/15ce171cc8041bac2d24823e271632db56eaebf1/integreat_cms/cms/views/statistics/statistics_actions.py#L92-L96) (also add `import asyncio`) and then show the corresponding div based on the return status code.

You can test the code by replacing
```
        async with aiohttp.ClientSession() as session:
```
by
```
        timeout = aiohttp.ClientTimeout(total=1)  # 1 sec timeout
        async with aiohttp.ClientSession(timeout=timeout) as session:
```
in the API manager.

2022-10-24 11:57 UTC, SteffiStuffel commented
@timoludwig thanks for explanation, adjusted it like you suggested.

2022-10-24 14:39 UTC, timoludwig requested changes
Thanks a lot! :+1:
Just found a small typo.

2022-10-24 14:39 UTC, timoludwig commented on integreat_cms/locale/de/LC_MESSAGES/django.po
> +msgstr "Der Statsitik-Server hat aktuell eine hohe Auslastung."
```suggestion
msgstr "Der Statistik-Server hat aktuell eine hohe Auslastung."
```
Small typo

2022-10-25 07:31 UTC, timoludwig approved these changes
Thanks! :ok_hand:

2022-10-25 08:45 UTC, merged