Reset `POT-Creation-Date` in translation file to avoid git conflicts
digitalfabrik/integreat-cms pull request #1850
Opened 2022-11-10 08:13 UTC by timoludwig

### Short description

I noticed that #1821 wasn't quite enough to reduce the git conflicts in the translation file due to the constantly changing date...
Since this information isn't really that useful anyway, I suggest to remove it in our dev tools.

### Proposed changes

- Reset `POT-Creation-Date` in translation file to avoid git conflicts

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2022-11-16 13:06 UTC, JoeyStk approved these changes
Thank you a lot! This is a very helpful PR :) 
I'm absolutely not a bash expert but as far as I can tell this looks good :) Maybe it would be good if someone with more experience in bash could also take a look at this :)

2022-11-16 13:09 UTC, timoludwig commented
> Maybe it would be good if someone with more experience could also take a look at this :)

@svenseeberg I can picture you really wanting to read some Bash :joy:

2022-11-18 13:13 UTC, charludo requested changes
Agree, really useful change!! Other than the one comment, LGTM

2022-11-18 13:13 UTC, charludo commented on dev-tools/translate.sh
> +    # Compile translation file
```suggestion
# Skip compilation if --skip-compile option is given
if [[ "$*" != *"--skip-compile"* ]]; then
    # Compile translation file
```
😉

2022-11-18 13:21 UTC, timoludwig commented on dev-tools/translate.sh
> +    # Compile translation file
oh haha :sweat_smile:

2022-11-18 13:30 UTC, david-venhoff commented on dev-tools/translate.sh
> +    # Compile translation file
Seems to still be `==`

2022-11-18 13:32 UTC, timoludwig commented on dev-tools/translate.sh
> +    # Compile translation file
:facepalm:

2022-11-18 13:38 UTC, david-venhoff approved these changes
Looks good to me now :tada:

2022-11-18 13:55 UTC, merged