Fix bulk archive/restore
digitalfabrik/integreat-cms pull request #1860
Opened 2022-11-14 11:53 UTC by david-venhoff

### Short description

This pr updates the bulk archive/restore actions to mimic the exact behavior of the per-object archive/restore actions.
That should fix archived pages showing up in the linkchecker.
This pr also fixes a related issue where links of an archived page, that is not a root-page, would not show up in the linkchecker after restoring the page.

### Proposed changes

- Add archive/restore methods to the page, event and poi models
- Use these methods from both bulk-actions and per-object actions
- When restoring pages, manually restore links if the page is not a root page

### Side effects

/

### Resolved issues

Fixes: ##1502

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2022-11-14 13:15 UTC, JoeyStk approved these changes
Thank you a lot! I've checked all the functionalities now, and as far I can tell everything works as expected :)

2022-11-14 16:33 UTC, timoludwig requested changes
Thanks a lot for spotting this problem! :pray:

The fix works almost as expected, however I found an edge case where it doesn't (when non-root pages are restored and its children are implicitly restored).

2022-11-17 15:55 UTC, david-venhoff commented on integreat_cms/cms/models/pages/page.py
> +                    translation.save(update_timestamp=False)
Can't think of a better solution, I just moved this part into its own method for readability...

2022-11-17 17:34 UTC, timoludwig approved these changes
Thanks a lot! :tada:
Works as expected and looks very clean! :+1:

2022-11-18 09:50 UTC, merged