Exclde users without page view permission from page specific permission
digitalfabrik/integreat-cms pull request #1901
Opened 2022-11-26 20:34 UTC by MizukiTemma

### Short description

This PR excludes users wihout the page view permission from the candidates list for page-specific permission grant and prevent such cases that pege-specific permissions are given to users who do not have the page view permission and therefore cannot access the pages. 

### Proposed changes

- Show in the candidates list only the users who have the permission to view pages.
- Check if the selected user has the permission to view pages before granting them a page specific edit permission. If not, show a message.

- Comming soon: test for page-specific permission

### Side effects

Not really a side effect but one notice.
- If an user with role Event Manager is added to an organisation and some pages are shared with their organisation, this means they are allowed to edit those pages but cannot see (access) the pages.

### Resolved issues

Fixes: #1900 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2022-12-13 13:03 UTC, JoeyStk requested changes
Hi,
thank you so much for this PR. I have a few notes. Other than those it worked as expected.

2022-12-13 15:27 UTC, MizukiTemma commented on integreat_cms/locale/de/LC_MESSAGES/django.po
> +"keine Seite sehen dürfen (z.B. Terminplaner)."
Fixed 🙂

2022-12-13 17:21 UTC, JoeyStk approved these changes

2022-12-17 17:44 UTC, timoludwig approved these changes
Thanks a lot! :+1:

Just found a small typo, other than that it looks good! :ok_hand:

2022-12-17 17:44 UTC, timoludwig commented on integreat_cms/cms/views/pages/page_actions.py
> +                "Page specific permissions cannot be granted to users who has no permission to view pages (e.g Event manager)."
```suggestion
                "Page-specific permissions cannot be granted to users who do not have permission to view pages (e.g event managers)."
```
small typo

2022-12-17 17:44 UTC, timoludwig commented on integreat_cms/locale/de/LC_MESSAGES/django.po
> +"sehen dürfen (z.B. Terminplaner), nicht gegeben werden."
```suggestion
"Page-specific permissions cannot be granted to users who do not have "
"permission to view pages (e.g event managers)."
msgstr ""
"Seitenspezifische Berechtigungen können nicht an Benutzer:innen vergeben "
"werden, die keine Seiten sehen dürfen (z.B. Terminplaner:innen)."
```

2022-12-18 12:41 UTC, merged