Fix mismatching columns in CSV export
digitalfabrik/integreat-cms pull request #1911
Opened 2022-11-29 13:40 UTC by Gaston69

### Short description
Bugfix csv-export of weekly statistics 

### Proposed changes
- Ensure export labels don't contain comma and corrupt CSV 

### Resolved issues

Fixes: #1701

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2022-11-29 13:54 UTC, Gaston69 commented
Peter solved it! :-)

2022-11-29 14:10 UTC, timoludwig commented
> Peter solved it! :-)

If you want to give him credit, you can also do `git commit --amend` and add

```
Co-authored-by: Peter Nerlich <nerlich@integreat-app.de>
```
to the commit message :wink:

(after that, you have to do `git push --force-with-lease` to overwrite the existing commit)

2022-11-30 10:02 UTC, PeterNerlich approved these changes
Since it seems simple enough, I'll add the first approve myself. We looked into it with four eyes, after all.

2022-11-30 13:00 UTC, timoludwig reviewed
Thanks, this fixes the issue! :+1:

Could you add a changelog entry for this?

2022-12-01 11:50 UTC, timoludwig requested changes
Thanks 👍
I know what is meant by the changelog entry because I know the context of the issue, but I think others might need a bit more info what this change is about.

2022-12-05 13:23 UTC, PeterNerlich commented on CHANGELOG.md
> +* [ [#1701](https://github.com/digitalfabrik/integreat-cms/issues/1701) ] Fix mismatching columns on CSV export of weekly statistics report
```suggestion
* [ [#1701](https://github.com/digitalfabrik/integreat-cms/issues/1701) ] Fix malformed CSV export on weekly statistics report
```

2022-12-05 13:28 UTC, PeterNerlich approved these changes

2022-12-05 14:49 UTC, timoludwig approved these changes

2022-12-05 16:03 UTC, merged