[Issue #1957] added keyboard shortcuts for icons in the editor
digitalfabrik/integreat-cms pull request #1962
Opened 2022-12-10 08:47 UTC by muddi900

### Short description
Add shortcuts for Adding icons in the editor.

### Proposed changes

-  Pressing `Alt+|+<number>` would insert the corresponding icons
- The sequence corresponds to the sequence in menu. eg. 1 for `pin`, 2 for `www`, etc.

### Side effects

- None

### Resolved issues

Fixes: #1957

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2022-12-10 12:25 UTC, MizukiTemma requested changes
Congratulation for your first PR in our repository 🎉 It's almost there 😃 

Additionaly to the suggestion in the code, I would like you to add an entry into CHANGELOG file under UNRELEASED.

2022-12-10 12:25 UTC, MizukiTemma commented on integreat_cms/static/src/js/forms/tinymce-init.ts
> +                    addIcon(editor, tinymceConfig, "pin");
```suggestion
                    let icon = tinymceConfig.getAttribute(`data-pin-icon-src`);
                    editor.insertContent(`<img src="${icon}" style="width:15px; height:15px">`);
```

The function "addIcon" adds an icon into the icon choice (the list which expands after clicking on "icon" menu) but not in the text.
Inserting an icon into the text can be achived, for example, like the suggestion above.

Could you apply the same change for the other icons too? You can also write a function for that if you find it not cool to repeat those code lines.

2022-12-12 14:57 UTC, MizukiTemma approved these changes
Very cool! Thank you 😃 

After squashing the commits (resolving conflicts if any occurs) I think this PR is ready to be merged 👍

2022-12-12 16:29 UTC, PeterNerlich approved these changes
Looks good to me, works as expected. Congrats!

2022-12-12 16:55 UTC, timoludwig requested changes
Thanks a lot, really cool feature! :+1:

> After squashing the commits

I agree, could you execute:
```
git rebase --interactive HEAD~2
```
and replace the second "pick" by "fixup" and save?
Then, you'd have to do:
```
git push --force-with-lease
```
To overwrite the existing commits.

> Additionaly to the suggestion in the code, I would like you to add an entry into CHANGELOG file under UNRELEASED.

Again, I agree, and this change has not yet been addressed.
Could you add the lines:
```
* [ [#1957](https://github.com/digitalfabrik/integreat-cms/issues/1957) ] Add keyboard shortcuts for icons in the editor

```
to the [CHANGELOG.md](https://github.com/digitalfabrik/integreat-cms/blob/develop/CHANGELOG.md) into the `UNRELEASED` section?

2022-12-18 00:28 UTC, timoludwig approved these changes
Thanks a lot! :+1:
I rebased your branch one last time and cleaned up the git history, now I think this is good to go! :tada:

(One optional idea I had was to somehow document this possibility, otherwise users don't know the keyboard combinations for the icons, but I guess we can also put this in our usage wiki.)

2022-12-18 00:28 UTC, merged