Make events, pois and pages uniform for observer users
digitalfabrik/integreat-cms pull request #1966
Opened 2022-12-12 17:03 UTC by david-venhoff

### Short description

There are some inconsistencies regarding the poi/event/page forms and list views for observer users.
This pr tries to fix that.

### Proposed changes

- Add no editing permission message to the location list view
- Disable the location form for users without editing permission
- Hide the create new poi/event buttons for users without the create object permission
- Don't show invalid warning in the event form for users without publishing and editing permissions

### Side effects

/

### Resolved issues

Fixes: #1945 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2022-12-13 14:07 UTC, JoeyStk requested changes
First of all, thank you a lot for this PR. I wasn't sure, if the PR is already up for review, but since it's not a draft I was guessing yes. 
So I think the functionality is there already and working as expected. All three requirements that were defined in the issue are met and work on my machine.
Other than that I only have thoughts on the failed test and I think you could squash your commit history a little bit, but I'm guessing that you already have an eye on that

2022-12-14 00:06 UTC, JoeyStk approved these changes
Thank you for updating, I think this looks good now! :)

2022-12-14 15:52 UTC, MizukiTemma requested changes
Thank you for your PR 🙂 It looks nice.

I have only a small suggestion.

2022-12-15 16:58 UTC, MizukiTemma approved these changes
Thank you! very cool 🚀 

After squashing the commits, it's ready for merge 😃

2022-12-15 18:17 UTC, merged