Rename role names
digitalfabrik/integreat-cms pull request #1971
Opened 2022-12-14 00:54 UTC by JoeyStk

### Short description
Rename two role names

### Proposed changes

- Rename editors to authors
- Rename publishers to editors

### Side effects
I hope none

### Resolved issues

Fixes: #1736 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2022-12-14 10:56 UTC, david-venhoff reviewed
Thanks! I tested the pr and it mostly works, but I found a problem with the migration: If a user has a page-specific permission to edit (not publish) a page then after the migration the user will have permission to also publish the page. This is because the `editors` field changes its meaning but keeps the same list of users. 
What should happen I think is that the users of the old `editor` field should get added to the `author` field and users of the `publisher` field should get added to the new `editors` field

2022-12-14 10:56 UTC, david-venhoff commented on integreat_cms/cms/forms/pages/page_form.py
>      def get_editor_queryset(self):
Maybe this function should be renamed? Right now I find it a bit confusing since it does not actually return the page editors anymore

2022-12-14 10:56 UTC, david-venhoff commented on integreat_cms/cms/forms/pages/page_form.py
>      def get_publisher_queryset(self):
Same here

2022-12-14 10:56 UTC, david-venhoff commented on integreat_cms/cms/rules.py
>  def is_page_editor(user, page):
These two methods could probably also get renamed

2022-12-14 11:03 UTC, david-venhoff reviewed
I think for consistency the other editor & publisher occurences in the top-comment in this file could also be changed, 
https://github.com/digitalfabrik/integreat-cms/blob/1e7e04e6ac81be0f8542e02276919560be9a4247/integreat_cms/cms/rules.py

2023-01-10 19:09 UTC, timoludwig requested changes
Thanks! :+1:

A few things were still missing, have a look at my suggestions below.

Also, there is this documentation patch which needs to be adapted as well:
https://github.com/digitalfabrik/integreat-cms/blob/develop/sphinx/patches/cms.diff

2023-01-10 19:09 UTC, timoludwig commented on integreat_cms/cms/templates/pages/_page_permission_table.html
> +        <i icon-name="plus-circle" class="mr-2"></i> {% translate "Add to authors" %}
```suggestion
        <i icon-name="plus-circle" class="mr-2"></i> {% translate "Add to editors" %}
```
In this particular case, the string was already correct (this is the text shown in the GUI which was fixed earlier)...

2023-01-10 19:09 UTC, timoludwig commented on integreat_cms/cms/migrations/0055_alter_author_and_editor_role_name.py
> +        ("cms", "0054_user_totp_key"),
```suggestion
        ("cms", "0055_track_region_deepl_api_usage"),
```

2023-04-04 11:17 UTC, MizukiTemma commented
@JoeyStk 

I fixed some fields that were not adjusted to the new role names so the test runs successfully.
If I have overlooked any logic or constraints and this is really not a solution, please drop the last 2 commits (I hope in this case the rebase won't harm anything at least).

2023-04-18 09:36 UTC, david-venhoff approved these changes
Thanks, I think this is good to go :rocket:

2023-04-18 09:56 UTC, merged