Make slugfield scrollable
digitalfabrik/integreat-cms pull request #1991
Opened 2023-01-10 11:02 UTC by PeterNerlich

### Short description

Make slugfield usable, even if URI prefix is very long.

### Proposed changes

- make slugfield scrollable by setting `overflow: auto` on the container
- ensure `input` is never at 0 width
- reduce label opacity to 60% for better distinction from input

### Side effects

- Other places using `.slug-field` will be affected. We estimate this to be fine.

### Resolved issues

Fixes: #1965 Combine recurrent events

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2023-01-10 18:08 UTC, timoludwig reviewed
Thanks a lot, this fixes the issue! :+1:

Could you add a changelog entry for this?

If the slug itself is longer than the input field, we have a "stacked" scrolling now, I was wondering whether we could combine this, so that the input field automatically grows when longer slugs are entered so we only have one layer of scrolling, but I can imagine this is probably a bit complicated, so only improve this if it doesn't cost you too much time :sweat_smile:
I'm already happy with the current solution! :+1:

![Screenshot 2023-01-10 at 19-04-46 Integreat Redaktionssystem](https://user-images.githubusercontent.com/16021269/211628347-70b77015-4620-4432-ba40-732df7588a6b.png)



> I guess the issue number mensioned in the PR description is not correct...

True, I fixed it

2023-01-10 19:27 UTC, timoludwig commented
Oh, and just a minor addition to my comment:
Please [separate the commit subject from body with a blank line](https://cbea.ms/git-commit/#separate), commit subjects with more than 72 characters are a bit hard to read:
![Screenshot 2023-01-10 at 20-22-35 Make slugfield scrollable by PeterNerlich · Pull Request #1991 · digitalfabrik_integreat-cms](https://user-images.githubusercontent.com/16021269/211642719-ce133a0e-f414-4c4b-a0b8-96c9f7deca16.png)

So I would use e.g. the following commit message instead:
```
Make slugfield scrollable

- Make slugfield scrollable by setting `overflow: auto` on the container
- Ensure `input` is never at 0 width
- Reduce label opacity to 60% for better distinction from input
```

2023-01-24 13:57 UTC, charludo approved these changes
LGTM, thanks!

2023-01-25 20:21 UTC, PeterNerlich commented
> If the slug itself is longer than the input field, we have a "stacked" scrolling now, I was wondering whether we could combine this, so that the input field automatically grows when longer slugs are entered so we only have one layer of scrolling, but I can imagine this is probably a bit complicated [...]

Yes, that is not possible without using JS/TypeScript magic that might act differently for different browsers, and since it would add probably quite a bunch of complexity and we don't have a very clear structure where this logic resides and how it is tested, if at all (at least that we know of), Ingo strongly favoured not investing more time, and I agree. I would have ideas how to hack it, though.

2023-01-25 20:24 UTC, timoludwig requested changes
> Ingo strongly favoured not investing more time, and I agree.

Sounds reasonable! Yes, this leaves us with the changelog entry and the commit message.

2023-01-25 21:06 UTC, timoludwig approved these changes
:+1:

2023-01-25 21:17 UTC, merged