Fix RTL text direction in PDF export
digitalfabrik/integreat-cms pull request #1996
Opened 2023-01-12 17:28 UTC by seluianova

### Short description
Somehow RTL languages are printed LTR in the PDF export

Title has correct direction, but content is incorrect:
![image](https://user-images.githubusercontent.com/115008338/212135414-5877c1ed-262f-4bd1-a431-bf15f651ae04.png)

### Proposed changes
Text direction broken when text passes through pdf_strip_fontstyles filter.
Adding "unescape" in return statement solves the issue.

### Side effects
I also updated pdfs in tests for other languages, because tests were failing.
But visually there was no difference except for Arabisch.
![pdf_test_result](https://user-images.githubusercontent.com/115008338/212136438-25a1e613-dd7a-4729-957c-b539fce1c899.jpg)

### Resolved issues
Partially fixes: #1954
(text direction is also wrong in ToC, but I will look into that separately)

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2023-01-17 13:55 UTC, JoeyStk requested changes
Thank you so much for this PR. It took me a while to wrap my head around the issue. For Arabic this works for me well now. However for Farsi I still have the issue. 
To me, the part that confused me the most, is that not only the direction of the entire line is mixed up, the direction is also mixed up inside a word. Since in Arabic and Farsi every letter looks different dependent on the position it has within a word, the words don't even look the same in Pdf and the editor.
![grafik](https://user-images.githubusercontent.com/72705147/212916385-53b11723-79ee-46ba-b807-58bf3023eb37.png)

2023-01-18 13:15 UTC, seluianova commented
@JoeyStk 
Cool finding, thanks. I was looking at Arabisch for so long that my eyes blurred.

I have just reviewed Arabic and Farsi one more time, and here is my summary:
As I see, issues below are actually the same for both Arabic and Farsi.

1. When Arabic/Farsi sentence **contains a Latin word**, weird metamorphoses take place:
I've marked identical pieces of text with the same color. So, we can see that these pieces of text change their position relative to the English word.
What is besonders strange to me - they change not their direction (they still RTL), but position in the sentence.

2. When there is a line break, the newline goes up, not down.
3. Bullet points are on the left, but should be on the right.

![image](https://user-images.githubusercontent.com/115008338/213180973-db89dbee-2c82-4ffb-8a72-4bd49bb0287e.png)

2023-01-18 14:52 UTC, svenseeberg commented
Have you tried setting an `dir="rtl"` attribute for a list item, for example? Would that improve the layout?

2023-01-18 15:40 UTC, seluianova commented
As we discussed on the team call:
- the first issue related to mixed content - we will leave it as is
- for second (line breaks) and third (bullet points) and ToC - I will raise issues for xhtml2pdf library

2023-01-18 15:52 UTC, JoeyStk approved these changes
For the new scope we're going for, everything seems to work.
I have tested it again and didn't run into issues :)

2023-01-26 14:43 UTC, timoludwig requested changes
Thanks a lot! :+1:
I hope that with this fix, the Arabic texts are at least partly readable with some effort...

2023-01-26 14:43 UTC, timoludwig commented on CHANGELOG.md
> +* [ [#1954](https://github.com/digitalfabrik/integreat-cms/issues/1954) ] Fix RTL text direction in PDF export
Due to the long time this PR is open now, this needs to be rebased and then moved up into the unreleased section again.

2023-01-30 11:04 UTC, timoludwig approved these changes

2023-01-30 11:19 UTC, merged