Show chapter for internal link suggestions
digitalfabrik/integreat-cms pull request #2016
Opened 2023-01-21 20:10 UTC by david-venhoff

### Short description

This pr changes the internal link suggestions to show the full path to an object translation instead of just its title.
As a sideeffect, the title will be shown in the backend language instead of the object translation's language.
I did not change the general search input feature, because there it is not ambiguous which object is which after performing the search.

### Proposed changes

- Add  a `path` to the JSON objects returned by `search_content_ajax`
- Display the path instead of the title in the internal link suggestions

### Side effects

/

### Resolved issues

Fixes: #1752

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2023-01-24 13:39 UTC, charludo submitted a review, later dismissed
This works really nice, except for the results in the wrong language. It's a bit unintuitive to search (e.g.) for "Willko" and receive "Welcome" or "Welcome -> ..." as a result. As a user I'd be worried that I'm linking to the English version of content even when I don't mean to.

Since `language_slug` is being passed to `search_content_ajax` in any case, would it maybe be possible to return the correct language paths?

2023-01-26 14:03 UTC, JoeyStk requested changes
Thank you a lot for this PR
I also thought it was strange that the languages get mixed. Other than that it also worked for me :)

2023-02-16 17:42 UTC, david-venhoff commented
Sorry for the delay..
The path should now be displayed in the current language.

2023-02-18 08:41 UTC, ulliholtgrave approved these changes
Thanks, Looks good to me and works nicely :+1:

2023-02-18 08:45 UTC, JoeyStk commented
Yes, I agree. The issue we had before is fixed now. Thank you a lot!

2023-02-18 08:45 UTC, JoeyStk approved these changes

2023-02-18 11:32 UTC, ulliholtgrave commented
Hey @david-venhoff Since we are adding your change to today's release, I'll take the liberty of merging your PR. Nevertheless, many many thanks for your work and best regards from the conference in Dortmund! :)

2023-02-18 11:33 UTC, merged

2023-02-18 16:29 UTC, david-venhoff commented
Thanks you! :)