Only allow staff members to use the SUMM AI bulk action
digitalfabrik/integreat-cms pull request #2104
Opened 2023-03-06 09:57 UTC by JoeyStk

### Short description
This PR restricts the usage of the SUMM AI bulk action to staff members only

### Proposed changes

- Add a check in the template if the user is staff member or not
- Add an entry to the changelog to let others teams know that we have improved this (please correct me, if we should remove the entry in case it's not meant to be seen by everyone) 

### Side effects
I think none. I tested it for a few roles and didn't notice any side effects. 
One thing we should keep in mind. As for now the SUMM AI function was disabled globally. So once this PR is merged, we could turn it on again

### Resolved issues

Fixes: #2065 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2023-03-06 10:04 UTC, timoludwig reviewed
I'm not sure if this is required anymore - if we don't implement #1727, then we need a bulk action for non-staff users...

2023-03-06 10:47 UTC, JoeyStk commented
After a quick chat with @dkehne I was reassured that this PR - although it's not very urgent - is still wanted, because it's the cleaner solution to our current workaround. At the moment there is still an edge case in which the municipalities have a short time window in which they theoretically could use the bulk action, although they shouldn't be able to. Sure, this isn't very likely but still at least a theoretic possibility

2023-03-06 10:52 UTC, timoludwig requested changes
Ok, but in the long term region managers should be able to use the bulk action, right? We only do the initial translations ourselves, but if they want to update the existing content, they should be able to do this on their own?

Apart from that: Please also implement the check in the bulk action view itself, otherwise this just makes the option invisible, but does not prevent users to use it.

2023-03-06 10:58 UTC, JoeyStk commented
Yes, that's how I understood it as well

Okay. I will do so. Thank you!

2023-03-07 11:00 UTC, osmers commented
Couldn't we just use the same principle for updating translations that we use for all other DeepL languages? If SUMM is active in the region and allowed for translation via the management section, then Deutsch (leicht) is an option that can be chosen on the page form?

2023-03-07 11:11 UTC, timoludwig commented
> Couldn't we just use the same principle for updating translations that we use for all other DeepL languages? If SUMM is active in the region and allowed for translation via the management section, then Deutsch (leicht) is an option that can be chosen on the page form?

@osmers Good idea, I opened #2110 for this.

2023-03-07 11:12 UTC, osmers commented
@timoludwig perfect - I also just asked Charlotte to post the latest design and ideas for language selection into the issue #1875 so that that is up to date

2023-03-08 13:56 UTC, charludo approved these changes
Very nice, works as expected! Apart from the one small comment, looks good to me! :)

2023-03-08 13:56 UTC, charludo commented on integreat_cms/cms/templates/pages/page_tree.html
> +                    {% if request.user.is_staff %}
I think you can combine these

2023-03-08 13:57 UTC, charludo commented on integreat_cms/cms/templates/pages/page_tree.html
>                  {% if SUMM_AI_ENABLED %}
I think you can combine this check with the one below.

2023-03-08 14:14 UTC, timoludwig requested changes

2023-03-08 14:14 UTC, timoludwig commented on integreat_cms/cms/views/bulk_action_views.py
> +            # Let the base view handle the redirect
```suggestion
        if not request.user.is_staff:
            raise PermissionDenied(
                f"Only staff users have the permission to bulk translate pages via SUMM.AI"
            )
        if not settings.SUMM_AI_ENABLED or not request.region.summ_ai_enabled:
            if not settings.SUMM_AI_ENABLED:
                logger.warning("SUMM.AI globally disabled")
            if not request.region.summ_ai_enabled:
                logger.warning("SUMM.AI disabled in %r", request.region)
            messages.error(request, _("Translations to Easy German are disabled"))
            return super().post(request, *args, **kwargs)
        # Collect the corresponding objects
        logger.info(
            "%r started SUMM.AI translation for: %r",
            request.user,
            self.get_queryset(),
        )
        api_client = SummAiApiClient(request, self.form)
        api_client.translate_queryset(self.get_queryset())
        # Let the base view handle the redirect
```
In my opinion, we should always raise errors when something is not supposed to happen - just silently doing nothing makes debugging very hard when something is not working.
So in this case, raising a permission denied error is the way to go I think.
(requires `from django.core.exceptions import PermissionDenied`)

2023-03-08 14:14 UTC, timoludwig commented on tests/summ_ai_api/summ_ai_test.py
> +        assert response.headers.get("location") == "/augsburg/pages/de/"
```suggestion
```
I think the `else` case is much more the expected outcome.

2023-03-08 15:52 UTC, timoludwig approved these changes

2023-03-08 18:32 UTC, merged