Add release notes bundling tool
digitalfabrik/integreat-cms pull request #2131
Opened 2023-03-20 15:07 UTC by timoludwig

### Short description

I was really annoyed by the changelog format and the constant merge conflicts, so I implemented a completely over-engineered release note tool.

To generate the good old markdown changelog, execute e.g.:
```
./tools/make_release_notes.sh --format=md --output=CHANGELOG.md
```

You can create new release notes by copying+pasting the existing ones, or by simply executing:
```
./tools/new_release_note.sh 1689 en "Changelog entries are now automatically genereated"
```
```
Checking if Integreat CMS is installed...
✔ Integreat CMS is installed
Creating new release note...
✔ The new release note has been generated:

integreat_cms/release_notes/current/unreleased/1689.yml
┌──────────────────────────────────────
│ en: Changelog entries are now automatically genereated
│ de: Changelog-Einträge werden nun automatisch generiert
└──────────────────────────────────────
```
or:
```
./tools/new_release_note.sh 1763 de "Das Änderungsprotokoll steht jetzt auch auf Deutsch zur Verfügung"
```
```
Checking if Integreat CMS is installed...
✔ Integreat CMS is installed
Creating new release note...
✔ The new release note has been generated:

integreat_cms/release_notes/current/unreleased/1763.yml
┌──────────────────────────────────────
│ en: The change log is now also available in German
│ de: Das Änderungsprotokoll steht jetzt auch auf Deutsch zur Verfügung
└──────────────────────────────────────
```
And if a DeepL auth key is set in the config file, the changelog entries are automatically translated.

### Proposed changes

- Split changelog into separate files
- Remove obsolete changelog checking script
- Add dev tool to build release notes
- Add dev tool to create new release note
- Adapt documentation script to new release notes
- Adapt CircleCI workflow to new release notes
- Show release notes in CMS

### Side effects

- Whether the release workflow works as expected remains to be seen

### Resolved issues

Fixes: #1689
Fixes: #1763

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2023-03-21 09:56 UTC, charludo commented on CHANGELOG.md
Is this intentional? If so, we should probably add the changelog to `.gitignore`

2023-03-21 10:12 UTC, charludo commented on tools/make_release_notes.sh
I have a couple of notes on the (default) behaviour and conventions here:
- to keep with `generate_documentation.sh`, maybe it would make sense to rename this script to `generate_release_notes.sh`? (just preference though)
- executing only `./tools/make_release_notes.sh` currently simply echoes the entire changelog. I don't see how this is useful. My suggestion would be to either:
    - only print the unreleased section, so we do not have to scroll endlessly up to see the entries we're most likely most interested in, and add a `--all` flag to get the current behaviour
    - **or** instead of echoing it, somehow open the output with `less` to make it easily navigatable and jump to the top of the output initially
    - **or** (and this is what I would prefer for daily workflow) make `--format=md --output=CHANGELOG.md` the default behaviour if no options are given. Then simply add  `--dry` and `--all` flags to echo only the unreleased section, or all sections in the console.

If it is worth the effort to implement these changes, I don't know; if we're not going to create the changelog ourselves before commiting (see the question about `.gitignore`) and this script is only used by CircleCI workflows, then probably not.

2023-03-21 10:13 UTC, timoludwig commented on CHANGELOG.md
Yes, it was intentional, but it's open for debate.
Do we want the file for people who visit our repo and want a quick overview without having to generate the file itself or look into the [documentation](https://digitalfabrik.github.io/integreat-cms/changelog.html)?
Or do we want to omit the file because it's redundant information?
Whether or not it belongs in the `.gitignore` depends on how often we're going to generate it - I personally see no use case to do this a lot locally, I guess I would just look into the docs or the new page in the CMS when I want the complete list.

2023-03-21 10:14 UTC, charludo requested changes
Very nice! 🎉 This will indeed prevent many merge conflicts 😄 
Just a couple of notes:

2023-03-21 10:16 UTC, charludo commented on CHANGELOG.md
Hm, it would still be nice to have the log visible in the repo, I think. Maybe an additional pre-commit hook?

2023-03-21 10:27 UTC, timoludwig commented on tools/make_release_notes.sh
> * to keep with `generate_documentation.sh`, maybe it would make sense to rename this script to `generate_release_notes.sh`? (just preference though)

I agree with the idea, but I would rather rename the docs script to `make_docs.sh` if that's ok?

> * executing only `./tools/make_release_notes.sh` currently simply echoes the entire changelog. I don't see how this is useful. My suggestion would be to either:
>       
>   * only print the unreleased section, so we do not have to scroll endlessly up to see the entries we're most likely most interested in, and add a `--all` flag to get the current behaviour
>   * **or** instead of echoing it, somehow open the output with `less` to make it easily navigatable and jump to the top of the output initially
>   * **or** (and this is what I would prefer for daily workflow) make `--format=md --output=CHANGELOG.md` the default behaviour if no options are given. Then simply add  `--dry` and `--all` flags to echo only the unreleased section, or all sections in the console.

I guess I chose "raw" and "all" as default values because that's how the script is used in the circleci workflow (it's easier to redirect stdout into a bash variable than generating a file and then read from it), but I agree the default values should match the daily use case, since the cirlceci config only has to be written once :grin:
Probably, I'd only print the latest version most of the time, and not the whole history...

2023-03-21 10:30 UTC, timoludwig commented on CHANGELOG.md
But if we keep it in the repo and modify it with each PR, this would defy the whole reason for a new tool, because we'd have the same merge conflicts as before (although it would be a little bit easier to resolve them)...
If we decide to keep it in the repo, I would only update it with every automated release commit (so it would not contain the unreleased section)...

2023-03-21 10:35 UTC, charludo commented on CHANGELOG.md
Oh... Good point. 

> I would only update it with every automated release commit (so it would not contain the unreleased section)...

Either that, or could we write an action to generate the changelog whenever a PR is merged into `develop`? Since that appears to be the default branch when visiting the repo, so this is where visitors would look for the log.

2023-03-21 11:04 UTC, charludo commented on CHANGELOG.md
> Maybe just a small placeholder file which links to the documentation?
> Or a symlink to the `ìntegreat_cms/release_notes` directory?

Those would work, yes! You're right, too much effort wouldn't be justified here.

2023-03-21 12:19 UTC, timoludwig commented on CHANGELOG.md
Hmm, symlinks don't quite work in the UI the way I hoped (clicking  on it just opens https://github.com/digitalfabrik/integreat-cms/blob/changelog-bundling/release-notes)...

Maybe a badge which links to the release notes?

[![Release Notes](https://img.shields.io/badge/%F0%9F%93%9C-release%20notes-blue)](https://digitalfabrik.github.io/integreat-cms/changelog.html)

2023-03-21 12:24 UTC, timoludwig commented on tools/make_release_notes.sh
I tried to change the behavior as described above, hope I didn't mess up :sweat_smile:

2023-03-21 12:28 UTC, charludo commented on CHANGELOG.md
Sure, why not! As long as the changelog is easy to find, any solution is probably fine.

2023-03-21 12:30 UTC, charludo commented on tools/make_release_notes.sh
Works like a charm! 🎉

2023-03-21 12:31 UTC, charludo approved these changes

2023-03-22 14:42 UTC, MizukiTemma approved these changes
Thank you 👍

2023-03-22 16:31 UTC, merged

2023-04-04 19:58 UTC, timoludwig commented
> So, where exactly is the config file again? A quick search in the documentation doesn't bring anything up. Is this a missing section?

In `/etc/integreat-cms.ini`

There's a small sentence here: https://digitalfabrik.github.io/integreat-cms/ref/integreat_cms.core.html#settings

But yeah, could probably be more prominent. And I'm not sure why the search isn't returning this result...