Add hix_bulk command
digitalfabrik/integreat-cms pull request #2179
Opened 2023-03-28 14:22 UTC by david-venhoff

### Short description

This pr adds a hix_bulk command which saves the hix store for all pages for which the score is missing.

### Proposed changes

- Add hix_bulk management command

### Side effects

/

### Resolved issues

Fixes: #2101 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2023-03-28 19:30 UTC, MizukiTemma commented
Do we need a test for the new command management in [tests/core/management/commands](https://github.com/digitalfabrik/integreat-cms/tree/develop/tests/core/management/commands) ?

2023-03-29 09:58 UTC, charludo approved these changes
Very nice! Works as expected. I think the regions-retrieving logic in `handle` could be simplified a little, though that may be at a loss of info in the error messages.

2023-03-29 11:33 UTC, timoludwig requested changes
Thanks a lot! :+1:

2023-03-29 14:20 UTC, david-venhoff commented on integreat_cms/core/management/commands/hix_bulk.py
> +
regarding 2: No, that was an error from me..

2023-03-29 16:16 UTC, timoludwig requested changes

2023-03-29 16:16 UTC, timoludwig commented on docs/src/management-commands.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
``hix_bulk``
~~~~~~~~~~~~
```
Ah, sorry for not noticing this earlier.
Not sure why the doc tool isn't complaining... the underline should match the heading itself.

2023-03-30 15:20 UTC, timoludwig commented
> Do we need a test for the new command in [tests/core/management/commands](https://github.com/digitalfabrik/integreat-cms/tree/develop/tests/core/management/commands) ?

Would definitely be cool, yes, but in sight of the deadline, I guess it would be fine to merge this first and hand in the tests later :see_no_evil:

2023-04-03 09:19 UTC, merged