Fix feedback filter error
digitalfabrik/integreat-cms pull request #2324
Opened 2023-06-24 13:51 UTC by MizukiTemma

### Short description

This PR fixes `NotSupportedError` which occurs in the feedback filter.

### Proposed changes

- Make an unrestricted query set after `.union()` so `select_related` can be operated on the query set (like in `get_pages` method of region).

### Side effects

- None (I hope), since no change on the filter query calcuration.

### Resolved issues

Fixes: #2273 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2023-06-24 16:00 UTC, david-venhoff commented
Looks mostly good to me, maybe you can move the code below https://github.com/digitalfabrik/integreat-cms/blob/9f272712025903f2ed4209998416ab030302a1a6/integreat_cms/cms/forms/feedback/region_feedback_filter_form.py#L116
so that we don't need to make a new database request every time?

2023-06-26 11:47 UTC, MizukiTemma commented
@david-venhoff Nice idea 🙂 applid!

2023-06-27 10:12 UTC, ulliholtgrave requested changes
Besides this small typo, this works as expected and looks good to me :+1:

2023-06-27 10:12 UTC, ulliholtgrave commented on integreat_cms/release_notes/current/unreleased/2273.yml
> +de: Behebe Fehler in Feedback Filter
```suggestion
de: Behebe Fehler im Feedback Filter
```

2023-06-27 11:04 UTC, ulliholtgrave approved these changes
Thanks, Looks good 👍

2023-06-27 11:07 UTC, merged