Add new icons for poicategory
digitalfabrik/integreat-cms pull request #2331
Opened 2023-07-03 11:08 UTC by JoeyStk

### Short description
This PR adds six new icons for poicategory

### Proposed changes

- Add svgs for the categories. I adapted the svgs a bit to fit the circle styling of the other svgs, as seen in the PR for the education category. I hope that was correct.
- I pushed a branch "add_new_poi_categories" where I also created the POI categories. As far as my understanding goes, we only need the icons for now (therefore this new branch)

### Side effects

- None I can think of

### Resolved issues

Fixes: #2270

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2023-07-03 11:34 UTC, timoludwig commented
> I pushed a branch "feature/add_new_poi_categories" where I also created the POI categories. As far as my understanding goes, we only need the icons for now (therefore this new branch)

This is a misunderstanding, the constants are not the poi categories, but only the choices for the icons. So yes, they need to be included in this pr, otherwise the icons are not usable.

And no, we don't need the actual poi categories in the repository, those are created in the database.

2023-07-03 12:14 UTC, JoeyStk commented
Thank you for clarifying. So it would have been better to use the other branch.

> And no, we don't need the actual poi categories in the repository, those are created in the database.

I'm not completely sure I understand correctly. For the icon names we still need a migration file, right?
If I'm reading this correctly I would add the icon names to the constants, add a migration file, extend the translation file and add a release note. Is that correct?

2023-07-03 13:04 UTC, timoludwig commented
> I'm not completely sure I understand correctly. For the icon names we still need a migration file, right? If I'm reading this correctly I would add the icon names to the constants, add a migration file, extend the translation file and add a release note. Is that correct?

Yes, I think that's it.

2023-07-03 13:54 UTC, JoeyStk commented
> Yes, I think that's it.

Okay, everything should be uploaded now :)

2023-07-03 21:33 UTC, timoludwig approved these changes
Thanks! :+1:

2023-07-03 21:33 UTC, timoludwig commented on integreat_cms/release_notes/current/unreleased/2270.yml
> +de: Füge neue Icons für POI-Kategoriesn hinzu
```suggestion
de: Füge neue Icons für POI-Kategorien hinzu
```

2023-07-04 08:54 UTC, ulliholtgrave requested changes
Please fix the typo and we are good to go :+1:

2023-07-04 08:54 UTC, ulliholtgrave commented on integreat_cms/locale/de/LC_MESSAGES/django.po
> +msgstr "Stuktur"
```suggestion
msgstr "Struktur"
```

2023-07-04 09:17 UTC, JoeyStk commented on integreat_cms/locale/de/LC_MESSAGES/django.po
> +msgstr "Stuktur"
Thank you, good catch :facepalm:

2023-07-04 09:19 UTC, ulliholtgrave approved these changes
Thanks, Looks good

2023-07-04 09:28 UTC, merged