Extend machine translation popup to events and pois
digitalfabrik/integreat-cms pull request #2339
Opened 2023-07-06 08:38 UTC by JoeyStk

### Short description
This PR extends the pre-existing machine translation popup from pages only also to POI and events. Since POI and events don't need a check for HIX, in these cases the HIX check is skipped.
(This PR is not yet fully ready for review)

### Proposed changes

- Extend the machine translation popup to POI and events
- Refactor the JS code a bit to make it independent from content type

### Side effects

- None of that I'm aware of at the moment

### Resolved issues

Fixes: #2314 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2023-07-08 12:35 UTC, MizukiTemma submitted a review, later dismissed
Thank you so much 😃 LGTM

2023-07-08 12:35 UTC, MizukiTemma commented on integreat_cms/cms/views/pois/poi_actions.py
> +    return JsonResponse(filtered_pois)
I don't think this is that bad 🙂

2023-07-08 19:40 UTC, MizukiTemma requested changes
Sorry for having once approved but requesting changes afterwords 🙏 

Those changes hopefully answer and fulfill your question to more efficient ajax call.

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/templates/_machine_translation_overlay.html
>                                  {% blocktranslate trimmed with hix_threshold=hix_threshold|floatformat:0 %}
```suggestion
                                {% blocktranslate trimmed with content_type=content_type hix_threshold=hix_threshold|floatformat:0 %}
```

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/templates/_machine_translation_overlay.html
> +                                {% translate "None of the selected {{ content_type }} has a source translation." %}
```suggestion
                                {% blocktranslate trimmed with content_type=content_type %}
                                    None of the selected {{ content_type }} has a source translation.
                                {% endblocktranslate %}
```

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/templates/events/event_list.html
> +                                data-url="{% url 'post_word_number_per_event' region_slug=request.region.slug language_slug=language.slug %}">
```suggestion
                                data-url="{% url 'post_word_number_per_event' region_slug=request.region.slug language_slug=language.slug model_type="event" %}">
```

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/templates/pois/poi_list.html
> +                                data-url="{% url 'post_word_number_per_poi' region_slug=request.region.slug language_slug=language.slug %}">
```suggestion
                                data-url="{% url 'post_word_number_per_poi' region_slug=request.region.slug language_slug=language.slug model_type="poi" %}">
```

In the same way the following should be applied in the page tree template:
data-url="{% url 'post_hix_and_word_number_per_page' region_slug=request.region.slug language_slug=language.slug model_type="page" %}"

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/urls/protected.py
> +                                        ),
```suggestion
                                        path(
                                            "<model_type>/auto-translate-words-per-poi/",
                                            utils.build_json_for_machine_translation,
                                            name="post_word_number_per_poi",
                                        ),
                                        path(
                                            "<model_type>/auto-translate-words-per-event/",
                                            utils.build_json_for_machine_translation,
                                            name="post_word_number_per_event",
                                        ),
```

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/urls/protected.py
> +                                        ),
Apply the following to the line 557 - 561:
                                        path(
                                            "<model_type>/auto-translate-hix-and-words-per-page/",
                                            utils.build_json_for_machine_translation,
                                            name="post_hix_and_word_number_per_page",
                                        ),

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/views/events/__init__.py
> +    post_word_number_per_event,
```suggestion

```

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/views/events/event_actions.py
> +from ..utils.machine_translations import buildJsonForMachineTranslation
```suggestion

```

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/views/events/event_actions.py
> +    return JsonResponse(filtered_events)
```suggestion


```

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/views/events/event_list_view.py
> +                "source_language": region.get_source_language(language.slug),
```suggestion
                "source_language": region.get_source_language(language.slug),
                "content_type": "events",
```

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/views/pages/page_actions.py
> +from ..utils.machine_translations import buildJsonForMachineTranslation
```suggestion

```

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/views/pages/page_actions.py
>  def post_hix_and_word_number_per_page(request, region_slug, language_slug):
We can omitt this

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/views/pois/__init__.py
> +    post_word_number_per_poi,
```suggestion

```

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/views/pois/poi_actions.py
> +    return JsonResponse(filtered_pois)
```suggestion

```

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/views/pois/poi_list_view.py
> +                "source_language": region.get_source_language(language.slug),
```suggestion
                "source_language": region.get_source_language(language.slug),
                "content_type": "locations",
```

Apply the same change to page tree view too.

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/views/utils/machine_translations.py
> +from ...models import Page
```suggestion
import json

from django.http import Http404, HttpResponseNotFound, JsonResponse

from ....textlab_api.utils import check_hix_score
from ...models import Event, Page, POI
```

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/views/utils/machine_translations.py
> +from ...models import Page
Add to __init__ file

from .machine_translations import build_json_for_machine_translation

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/views/utils/machine_translations.py
> +    request, language_slug, model, hix_check_required=False
```suggestion
def build_json_for_machine_translation(
    request, region_slug, language_slug, model_type
```

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/views/utils/machine_translations.py
> +    )
```suggestion
    model_types = {
        "event": Event,
        "page": Page,
        "poi": POI,
    }

    selected_content_ids = json.loads(request.body.decode("utf-8"))
    selected_content = model_types[model_type].objects.filter(region=request.region, id__in=selected_content_ids)
```

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/views/utils/machine_translations.py
> +        ):
```suggestion
        if (
            source_translation
            and check_hix_score(request, source_translation, show_message=False)
        ):
```

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/cms/views/utils/machine_translations.py
> +    return filtered_content
```suggestion
    return JsonResponse(filtered_content)
```

2023-07-08 19:40 UTC, MizukiTemma commented on integreat_cms/locale/de/LC_MESSAGES/django.po
> +msgstr "Keine der ausgewählten {{ content_type }} hat eine Quellübersetzung."
```suggestion
#, python-format
msgid "None of the selected %(content_type)s has a source translation."
msgstr "Keine der ausgewählten %(content_type)s hat eine Quellübersetzung."
```

2023-07-08 19:42 UTC, MizukiTemma commented on integreat_cms/cms/views/pois/poi_actions.py
> +    return JsonResponse(filtered_pois)
Though found a way to minimalize it. Please find them in the code suggestions. I hope those work fine 🙂

2023-07-10 09:28 UTC, JoeyStk commented on integreat_cms/cms/views/pois/poi_actions.py
> +    return JsonResponse(filtered_pois)
Thank you for the suggestions, they are applied now :)

2023-07-10 13:36 UTC, MizukiTemma approved these changes
Thank you 🎉

2023-07-25 17:43 UTC, PeterNerlich requested changes
I'm not figuring out how to get this to run today anymore, so here is some preliminary feedback, just from looking at the code.

All in all this looks good, I just have a ton of nit picky stuff about variable names and URL lookup names (where my suggestion might also be questionable, looking back on it) and stuff, and I didn't even get started on proper pluralisation because I have no clue about that for now.

2023-07-25 17:43 UTC, PeterNerlich commented on integreat_cms/cms/templates/_machine_translation_overlay.html
> +                                {% blocktranslate trimmed with content_type=content_type %}
```suggestion
                                {% blocktranslate trimmed %}
```

2023-07-25 17:43 UTC, PeterNerlich commented on integreat_cms/cms/templates/_machine_translation_overlay.html
> +                                {% blocktranslate trimmed with content_type=content_type hix_threshold=hix_threshold|floatformat:0 %}
```suggestion
                                {% blocktranslate trimmed hix_threshold=hix_threshold|floatformat:0 %}
```

2023-07-25 17:43 UTC, PeterNerlich commented on integreat_cms/cms/templates/_machine_translation_overlay.html
> +                            {% blocktranslate trimmed with content_type=content_type %}
```suggestion
                            {% blocktranslate trimmed %}
```

2023-08-14 19:39 UTC, PeterNerlich approved these changes
I don't feel like I tested it thoroughly now, but I have no objections.

The only one minor thing that I noticed is that we use `overflow: scroll;` on the popup, which makes my chromium *always* display scroll bars, even if you cannot use them because the content entirely fits in the container. My firefox doesn't show that behaviour, but the scrollbars there are the overlay type that don't actually take up space but render on top of the content, but I don't know whether that is a configuration thing.
Using `overflow: auto;` would fix this and make both browser use whatever native scroll bars they use only then, when there is actually content to scroll through, but I had a look and we use tailwinds `.overflow-scroll` in various other places as well while we don't use `.overflow-auto` anywhere. So I suspect this is, if anything, a separate issue for the backlog.

2023-08-16 12:55 UTC, merged