Add graceful error messages when sending mail
digitalfabrik/integreat-cms pull request #2349
Opened 2023-07-17 16:07 UTC by PeterNerlich

### Short description

Display a graceful error message instead of Internal Server Error when failing to send mail.

### Proposed changes

- Catch multiple types of exceptions
  - *BadHeaderError (was already there, now giving slightly more context)*
  - SMTPAuthenticationError (special SMTPException)
  - SMTPException
  - ConnectionRefusedError
- Every exception gets the same base message that already existed, with a brief hint on what the actual problem is. This might make them more content (they get a feeling of knowing what's wrong, not only that something is wrong) and possibly speed up the investigation process when they report it.

### Side effects

- Only a few hours ago I claimed I would be focusing on Reviews and not submit any new PRs for now. With this I kinda loose credibility, don't I? :sweat_smile: 
- Code should be fine

### Resolved issues

Fixes: #2046 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2023-07-17 16:28 UTC, timoludwig requested changes
Thanks a lot! :+1:

I think it would make more sense to move the `try`-`except` block into [/integreat_cms/cms/utils/email_utils.py](https://github.com/digitalfabrik/integreat-cms/blob/7a8fda13ca5b35a90c79077174335e01c87beb2d/integreat_cms/cms/utils/email_utils.py#L73), because then the error handling could also be used for the password reset.

2023-07-17 16:28 UTC, timoludwig commented on integreat_cms/cms/utils/welcome_mail_utils.py
> +        logger.exception(e)
```suggestion
        logger.error(e)
```
I think with these specific error messages, we don't need the whole stack trace from the smtp library, just the error is enough.

2023-07-17 16:28 UTC, timoludwig commented on integreat_cms/cms/utils/welcome_mail_utils.py
> +        logger.exception(e)
```suggestion
        logger.error(e)
```

2023-07-17 16:28 UTC, timoludwig commented on integreat_cms/cms/utils/welcome_mail_utils.py
> +        logger.exception(e)
```suggestion
        logger.error(e)
```

2023-07-17 16:28 UTC, timoludwig commented on integreat_cms/release_notes/current/unreleased/2046.yml
> +de: Zeige Fehlermeldung bei Fehlschlag, Mails zu verschicken
```suggestion
de: Zeige hilfreichere Fehlermeldung, wenn das Senden von E-Mails fehlschlägt
```

2023-07-17 16:28 UTC, timoludwig commented on integreat_cms/locale/de/LC_MESSAGES/django.po
> +msgstr "Fehlerhafte Kopfdaten."
```suggestion
msgstr "Fehlerhafte Header-Daten."
```

2023-07-17 22:03 UTC, PeterNerlich commented
> I think it would make more sense to move the `try`-`except` block into [/integreat_cms/cms/utils/email_utils.py](https://github.com/digitalfabrik/integreat-cms/blob/7a8fda13ca5b35a90c79077174335e01c87beb2d/integreat_cms/cms/utils/email_utils.py#L73), because then the error handling could also be used for the password reset.

Funny you should mention that, Ingo and I went back and forth about this for a while, but finally opted to leave it one step higher in the call stack because we would have to pass `request` and `debug_mail_type` in there and were unsure whether this is valid in all uses of this utility function. E.g. we could imagine a cron job or management command using that. But you can probably shine a light on whether this poses a problem or not.

2023-07-17 22:59 UTC, timoludwig commented
> Funny you should mention that, Ingo and I went back and forth about this for a while, but finally opted to leave it one step higher in the call stack because we would have to pass `request` and `debug_mail_type` in there and were unsure whether this is valid in all uses of this utility function. E.g. we could imagine a cron job or management command using that. But you can probably shine a light on whether this poses a problem or not.

Ah, sorry, I missed that it created quite a few problems to pass the `request` object to the util function (I think `debug_mail_type` is irrelevant since the user knows what type of email they were just sending, so I think it's not required to add that info if it's too complicated). I agree that it makes sense to keep the util function agnostic of the http request.

Ok, now thinking about it, I guess we need to add another `try`/`except` block in the password reset view here:

https://github.com/digitalfabrik/integreat-cms/blob/7a8fda13ca5b35a90c79077174335e01c87beb2d/integreat_cms/cms/views/authentication/password_reset_view.py#L82

something along the lines of:

```
try:
    return super().form_valid(form)
except RuntimeError as e:
    messages.error(request, e)
    return redirect("public:password_reset")
```

Also, to de-duplicate all the different exception messages, I think it would be fine to catch and unify these in the email utils, and just raise one type of error (e.g. `RuntimeError`) there, and then catch the runtime error in both the password reset view and the welcome/activation mail view.

2023-07-18 20:50 UTC, timoludwig commented
> I implemented it for the password reset view, but when testing I wondered whether this is actually what we want. The success message always says "if an account for that email exists…", but the error message will only appear if we actually send an email. The relevance of this is probably very low, but I can't help but wonder how the proper solution for this should actually look like

Thanks! This is exactly how I had envisioned it. It is intended that we don't show an error for non-existing emails to make it harder to brute-force registered email addresses.

After fixing the two remaining small suggestions and cleaning up the git history, I think this is ready to be merged! :+1:

2023-07-18 21:00 UTC, PeterNerlich commented
> It is intended that we don't show an error for non-existing emails to make it harder to brute-force registered email addresses.

But now one can still brute-force for registered email addresses if there is a system configuration error or the email server is unreachable, since those errors will only occur for actual email send attempts, correct? Though it is not really a regression to the HTTP 500 thrown before, it does now explicitly state that trying to send the email was what caused a problem.

2023-07-18 21:04 UTC, timoludwig commented
> But now one can still brute-force for registered email addresses if there is a system configuration error or the email server is unreachable, since those errors will only occur for actual email send attempts, correct?

Ok true, though I think we can live with this :smiling_face_with_tear:

2023-07-19 10:00 UTC, timoludwig requested changes
@PeterNerlich could you clean up the git history a bit? Splitting the two commits for welcome email and password reset is fine for me, but the translations and release notes should be part of the commit they are actually referring to.

2023-07-19 10:12 UTC, PeterNerlich commented
In that case, it's easiest to squash it all together, since the translations and release notes are also relevant to the password reset form

2023-07-19 10:13 UTC, timoludwig commented
> In that case, it's easiest to squash it all together, since the translations and release notes are also relevant to the password reset form

I agree.

2023-07-19 10:14 UTC, timoludwig approved these changes
Great, thanks! :tada:

2023-07-19 10:25 UTC, ulliholtgrave approved these changes
Thanks, I only looked on the code and didn't provoke the Exceptions. However, I thinks that the differentiation is a great improvement to the current state :+1:

2023-07-19 11:29 UTC, merged