Fix pylint deprecation warnings
digitalfabrik/integreat-cms pull request #2407
Opened 2023-08-27 10:11 UTC by ulliholtgrave

### Short description

I was kinda annoyed by the `distutils` deprecation warning and solved them for our project by following the PEP 632 recommendations (see [https://peps.python.org/pep-0632/](https://peps.python.org/pep-0632/)).

### Proposed changes

- Add a general utils file to the top level of our project if our modules are needing more shared methods.
- 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2023-08-27 11:42 UTC, timobrembeck requested changes

2023-08-27 11:42 UTC, timobrembeck commented on integreat_cms/default_utils.py
Just a matter of preference, but I think plain `utils.py` is sufficient as filename, no need for the `default_` prefix.
We also used this convention in the other Django apps, so we either have a single `utils.py` file or a `utils` directory containing multiple utils with prefixes...

2023-08-27 11:42 UTC, timobrembeck commented on integreat_cms/release_notes/current/unreleased/2406.yml
Implementation details are irrelevant for the end users and other teams, so I would suggest to remove this release note to stay consistent with our previous guidelines.

2023-08-27 12:49 UTC, timobrembeck commented on integreat_cms/utils.py
Sorry, I think I have expressed myself a little misleadingly... I think the location of the file inside the `core` directory was better than in the root directory, I just suggested it to rename it. So now the name is better but I'd suggest to move it back into the core dir :see_no_evil:

2023-08-27 12:50 UTC, timobrembeck requested changes

2023-08-27 12:50 UTC, timobrembeck commented on integreat_cms/api/v3/locations.py
> +from ...default_utils import strtobool
```suggestion
from ...core.utils import strtobool
```

2023-08-27 12:50 UTC, timobrembeck commented on integreat_cms/core/settings.py
>  from .logging_formatter import ColorFormatter, RequestFormatter
```suggestion
from .logging_formatter import ColorFormatter, RequestFormatter
from .utils import strtobool
```

2023-08-27 15:15 UTC, timobrembeck approved these changes

2023-08-28 07:10 UTC, PeterNerlich approved these changes
LGTM!

2023-08-28 08:06 UTC, merged