Add empty tag to empty pages with only archived subpages
digitalfabrik/integreat-cms pull request #2479
Opened 2023-10-24 10:57 UTC by MizukiTemma

### Short description

This PR adds an empty tag to empty pages whose subpages are all archived.

### Proposed changes

- Add to the condition for the empty tag the case where all the subpages are archived 
- Adjust `get_non_archived_children` to choose whether the parent page should be included or not.

### Side effects

- I hope none
- but I may have misunderstood the desired behaviour 🙈 

### Resolved issues

Fixes: #1175 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2023-11-11 11:43 UTC, david-venhoff approved these changes
Thanks, LGTM!

2023-11-13 13:42 UTC, timobrembeck commented on integreat_cms/cms/models/pages/page.py
> +    def get_non_archived_children(self, include_parent: bool | None = True) -> Iterator[Page]:
```suggestion
    def get_non_archived_children(self, include_parent: bool = True) -> Iterator[Page]:
```
If an optional parameter has a default value that is not `None`, we don't need the `| None` as type hint: Either, `True`/`False` is directly passed, then it's a `bool`, or it is omitted, then it is set to `True` which is also a `bool`. So the variable `include_parent`  is always a `bool` and never `None`.

2023-11-17 06:59 UTC, sarahsporck approved these changes
Implementation looks good 👍🏼. 
Would be great to have tests for the tags though, but if it is not in scope for this pr, this can also be done later.

2023-11-17 12:31 UTC, timobrembeck requested changes
Thanks! :+1:
I see a slight potential for improving the performance, and could you remove the "TODO" comment in line 269?

2023-11-17 12:31 UTC, timobrembeck commented on integreat_cms/cms/models/pages/page_translation.py
> +            or not any(self.page.get_non_archived_children(include_parent=False))
```suggestion
            or not self.page.children.filter(explicitly_archived=False).exists()
```
I think it's unnecessary to query the entire subtree of a page to determine whether it has archived descendants. Shouldn't it be sufficient to look at the direct children, and if no un-archived direct children exist, then we know that all its grand-children are either explicitly or implicitly archived?

2023-11-17 13:51 UTC, MizukiTemma commented
> Implementation looks good 👍🏼. Would be great to have tests for the tags though, but if it is not in scope for this pr, this can also be done later.

hmm 🤔 I don't think test for the tags can be well integreated into the current view based test... I'll leave it as it is for now.

2023-11-17 14:14 UTC, timobrembeck requested changes

2023-11-17 14:14 UTC, timobrembeck commented on integreat_cms/cms/models/pages/page.py
> +    def get_non_archived_children(self, include_parent: bool = True) -> Iterator[Page]:
```suggestion
    def get_non_archived_children(self) -> Iterator[Page]:
```
Could you also revert this change that is no longer needed?

2023-11-17 14:14 UTC, timobrembeck commented on integreat_cms/cms/models/pages/page.py
> +            elif include_parent or not child_page == self:
```suggestion
            else:
```

2023-11-17 14:14 UTC, timobrembeck commented on integreat_cms/cms/models/pages/page_translation.py
> +        * Empty: if the page contains no text and has no subpages
```suggestion
        * Empty: if the page contains no text and has no non-archived subpages
```

2023-11-17 17:16 UTC, timobrembeck reviewed
Thanks! After squashing the commits, I have no further objections :grin:

2023-11-17 18:17 UTC, timobrembeck approved these changes

2023-11-17 18:24 UTC, merged