Fix line break in dashboard sections
digitalfabrik/integreat-cms pull request #2526
Opened 2023-11-03 15:49 UTC by JoeyStk

### Short description

This PR aims to fix the line break in dashboard sections. It's caused due to the width of the checkmark icon.

### Proposed changes

- Add basis class to the rows

### Side effects

- I wasn't able to test this on a screen larger than 14". If changes are needed to be made, someone else would need to take over from me :/
- There are some sizes (for example 1280px where the buttons don't look great. But I'm not sure how to improve it with flex. Maybe it would be better to switch to grid?

### Resolved issues

Fixes: #2522 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2023-11-03 16:01 UTC, timobrembeck requested changes

2023-11-03 16:01 UTC, timobrembeck commented on integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_automatically_saved_pages_row.html
> +        <a class="btn !rounded-full ml-2"
```suggestion
        <a class="btn !rounded-full"
```

2023-11-03 16:01 UTC, timobrembeck commented on integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_broken_links_row.html
> +        <a class="btn !rounded-full ml-2"
```suggestion
        <a class="btn !rounded-full"
```

2023-11-03 16:01 UTC, timobrembeck commented on integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_low_hix_row.html
> +        <a class="btn !rounded-full ml-2"
```suggestion
        <a class="btn !rounded-full"
```

2023-11-03 16:01 UTC, timobrembeck commented on integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_outdated_pages_row.html
> +        <a class="btn !rounded-full ml-2"
```suggestion
        <a class="btn !rounded-full"
```

2023-11-03 16:01 UTC, timobrembeck commented on integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_unread_feedback_row.html
> +           class="btn !rounded-full ml-2">
```suggestion
           class="btn !rounded-full">
```

2023-11-03 16:01 UTC, timobrembeck commented on integreat_cms/cms/templates/dashboard/todo_dashboard_rows/_unreviewed_pages_row.html
> +        <a class="btn !rounded-full ml-2"
```suggestion
        <a class="btn !rounded-full"
```

2023-11-03 17:01 UTC, JoeyStk commented
Oh yeah, much better! Thank you!
However, I'm still not 100% satisfied with this view. 

- Do you think it's okay if I change the margin to ml-6 so it matches the margin between the icon on the left side and the text?
- And secondly, the checkmark icon is not centered (s. screenshot). One idea could be to adjust the margin from the right from mr-12 to mr-9 in all sub-templates. But it's still not exact and also not dynamic in case we change the text inside the button. My initial idea was to create a div that matches the width of the button and then center the icon within that width, but I couldn't make it work - it only made it worse. Do you have an idea how to fix this? My only other idea would have been to switch to grid but I'm not sure if that's worth the effort :thinking: 

Thank you a lot in advance!

2023-11-03 18:00 UTC, timobrembeck commented
> Do you think it's okay if I change the margin to ml-6 so it matches the margin between the icon on the left side and the text?

Yes, good idea! :+1:

> And secondly, the checkmark icon is not centered (s. screenshot). One idea could be to adjust the margin from the right from mr-12 to mr-9 in all sub-templates. But it's still not exact and also not dynamic in case we change the text inside the button. My initial idea was to create a div that matches the width of the button and then center the icon within that width, but I couldn't make it work - it only made it worse. Do you have an idea how to fix this? My only other idea would have been to switch to grid but I'm not sure if that's worth the effort 🤔

Ah, ok yeah I didn't think about this problem. If all buttons are aligned to the right, it's a bit weird if the check mark floats somewhere near the center of the buttons (but not all buttons have the same width, so it's never going to be exact...)

What do you think about using `basis-full` on the left column and adding `justify-center` and `w-36` to the right column? To me, that looks quite clean and does not waste screen space...

I would maybe also increase the size of the icons a bit (e.g. `h-8 w-8`) and make them green (`text-green-500`) as suggested in the [initial design](https://www.figma.com/file/6U7R7Xj4wL7sbjxKRmOG9D/CMS-Project?type=design&node-id=533%3A3489&mode=dev)?

2023-11-04 10:01 UTC, timobrembeck approved these changes
Thanks, I think this looks cool! :+1:

2023-11-05 14:39 UTC, MizukiTemma requested changes
Looks good 🙂 Thank you.

There is only one very mean request: put `, ` in the translation "gespeichert. Bitte vergessen Sie nicht die Seite zu veröffentlichen, sobald "

2023-11-05 16:05 UTC, JoeyStk commented
> There is only one very mean request: put , in the translation "gespeichert. Bitte vergessen Sie nicht die Seite zu veröffentlichen, sobald "

Oh, very good catch! Thank you so much :)

2023-11-05 16:14 UTC, MizukiTemma approved these changes
👍

2023-11-06 09:34 UTC, merged