Remove duplicate 'x' in search fields
digitalfabrik/integreat-cms pull request #2608
Opened 2024-01-15 12:50 UTC by charludo

### Short description

In Chromium-based browsers, a duplicate 'x' for clearing search fields was inserted by the browser itself. This PR adds styling to hide this element.

### Proposed changes

- apply `display: none` to the duplicate 'x'

### Side effects

- none 

### Resolved issues

Fixes: #2604 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2024-01-15 20:44 UTC, ulliholtgrave approved these changes
Good old webkit doing stuff :D :+1:

2024-01-16 10:15 UTC, MizukiTemma requested changes
Thank you for quick fix 👍 

hmm, the problem seems to be fixed in Edge but not in Chrome and Opera 🥺

2024-01-16 11:25 UTC, charludo commented
> Thank you for quick fix 👍
> 
> hmm, the problem seems to be fixed in Edge but not in Chrome and Opera 🥺

Thanks for pointing this out... I tried it yesterday in Chromium, but it looks like this:
```css
::-ms-clear {
    display: none;
}

::-webkit-search-decoration,
::-webkit-search-cancel-button,
::-webkit-search-results-button,
::-webkit-search-results-decoration {
    display: none;
}
```
does work, while the "simplified" version
```css
::-ms-clear,
::-webkit-search-decoration,
::-webkit-search-cancel-button,
::-webkit-search-results-button,
::-webkit-search-results-decoration {
    display: none;
}
```
does not... for whatever reason 😅

2024-01-16 11:33 UTC, MizukiTemma approved these changes
Yes, looks as expected 😺

2024-01-20 08:25 UTC, merged