Update page link before submitting page form
digitalfabrik/integreat-cms pull request #2636
Opened 2024-02-05 14:12 UTC by charludo

### Short description

I had a bit of trouble reproducing the issue. The only way I could trigger it was by entering Firefox's Responsive Design Mode and enabling Touch Simulation (though I suspect this might also happen on real touch devices).

I don't think this is worth an entry in the change log, this really is an edge case.

### Proposed changes

- if the content form is submitted while we're still waiting on a response for `slugify`, prevent the submission, then trigger it again once the previous call completed.

### Side effects

- hopefully not

### Resolved issues

Fixes: #2624

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2024-02-19 13:36 UTC, seluianova requested changes
> though I suspect this might also happen on real touch devices

Right, I was able to reproduce the issue using the touch screen.

As I can see now, the proposed changes fix that! 🚀 
I think this can be applied to events and locations as well.

**UPD**.
And the same problem occurs when saving to draft.

2024-02-21 09:29 UTC, charludo commented
> I think this can be applied to events and locations as well.
> 
> **UPD**. And the same problem occurs when saving to draft or submitting for approval.

Right, thanks for catching that!

I've added a more general solution.

2024-02-22 13:08 UTC, seluianova commented on integreat_cms/static/src/js/forms/prevent-premature-submission.ts
> +export default class SubmissionPrevention {
Maybe add some short clarification here? Because from the code itself it is rather difficult to understand why it was added

2024-02-22 14:04 UTC, seluianova requested changes
Opps, sorry, I actually found one issue:
"Submit for approval" action has been broken for Observer
![image](https://github.com/digitalfabrik/integreat-cms/assets/115008338/812533d0-e097-4ce7-aa22-bfd9e88aaafb)
It can be reproduced, if Observer changes the page title.

2024-03-26 10:26 UTC, charludo commented
> Opps, sorry, I actually found one issue: "Submit for approval" action has been broken for Observer 
[...]
It can be reproduced, if Observer changes the page title.

Sorry for taking so long to get back to you.

Looks like this also happens on the develop branch, so it's unrelated to the changes. However, I think it might be intentional - @osmers, should Observers be able to change titles of pages they can edit?

If yes, I can open a new issue;
if no, I'd use this PR to set the field disabled for Observers, if that's all right with both of you.

2024-03-26 10:34 UTC, seluianova commented
> Looks like this also happens on the develop branch, so it's unrelated to the changes

I have re-checked:
The error on the screen is reproduced on develop, so it's really unrelated.
But the action itself works on develop - I can submit a title change for approval.

2024-03-26 10:38 UTC, seluianova commented
> Looks like this also happens on the develop branch, so it's unrelated to the changes

I have re-checked:
The error on the screen is reproduced on develop, so it's really unrelated.
But the action itself works on develop - I can submit a title change for approval now.

But right, if the title field should be disabled, it will solve the problem anyway :)

2024-03-26 11:18 UTC, charludo commented
> > Looks like this also happens on the develop branch, so it's unrelated to the changes
> 
> I have re-checked: The error on the screen is reproduced on develop, so it's really unrelated. But the action itself works on develop - I can submit a title change for approval now.
> 
> But right, if the title field should be disabled, it will solve the problem anyway :)

AH, I mistakenly thought Observers could not change the title, but in fact it's just that they can't directly change the link (so the automatic link update is, of course, not an issue at all here.

I've removed the submission prevention for "submit for approval".

2024-03-26 13:37 UTC, osmers commented
> > > Looks like this also happens on the develop branch, so it's unrelated to the changes
> > 
> > 
> > I have re-checked: The error on the screen is reproduced on develop, so it's really unrelated. But the action itself works on develop - I can submit a title change for approval now.
> > But right, if the title field should be disabled, it will solve the problem anyway :)
> 
> AH, I mistakenly thought Observers could not change the title, but in fact it's just that they can't directly change the link (so the automatic link update is, of course, not an issue at all here.
> 
> I've removed the submission prevention for "submit for approval".

I think it makes sense that observers can change the title of the page they are allowed to edit. Either they were given the rights to publish right away which means they are trusted to only do what's expected or they can only submit for review, in which case the changes to the title could be rejected if not wanted, right?

2024-03-27 10:54 UTC, seluianova commented
Observer can now submit a title change for approval (the same behavior as in develop) ✅
But the original problem remains for the "Submit for approval" action:
- login as Author 
- edit some page title
- click 'Submit for approval' using the touch screen
--> the page is saved with a new title, but the link is not updated

2024-04-29 13:28 UTC, charludo commented
> > I mistakenly thought Observers could not change the title, but in fact it's just that they can't directly change the link
> 
> Actually it seems they can change a link directly (submit a link change for approval), I have just checked in develop.

Alright. I think everythin is working now the same as on develop, plus touch screens work. However, I have not fixed the underlying bug (which is that the `slugify_ajax` endpoint raises `PermissionDenied` for observers because they are not allowed to edit objects), but instead just moved the release of the submission lock to a `finally()` block. This way the `fetch` still throws an unhandled error, just like on develop.

I think we should either
- keep the `PermissionDenied` but handle it "properly" (aka hide it / prevent logging to console), or
- change the required permission in `slugify_ajax.py` to `view_page` etc.

I like the second option better, but wasn't sure if there's some unintended consequences.

2024-05-07 07:12 UTC, JoeyStk approved these changes
Thank you very much! Looks really good! I really would like to have a test for this, but since we don't have JS tests yet, I think we can give it a pass

2024-05-07 07:43 UTC, charludo commented
> Thank you very much! Looks really good! I really would like to have a test for this, but since we don't have JS tests yet, I think we can give it a pass

Yes, fair 😅 Any suggestions on how to handle the `PermissionDenied`?

2024-05-07 08:00 UTC, JoeyStk commented
Oh sorry, I forgot to mention that. I also tend towards the second option. I think the PermissionDenied indicates that somewhere we have a logical thinking error in our permissions. I think changing the permission should be the right thing :thinking:

2024-05-07 12:37 UTC, seluianova commented
> change the required permission in slugify_ajax.py to view_page etc.

Sounds better to me, because if Observer has the right to modify the link directly, then modifying the link should also work through ajax. I think that would be more consistent.

2024-05-08 06:45 UTC, charludo commented
Alright, I've lowered the required permissions. 

"Worst case" someone can generate a slug for a content objects they shouldn't - but since the function only returns the generated slug, not actually saves it, I think that's OK.

I have also let the client-side error handling in, just in case anything else occurs server-side we still release the submission lock.

2024-05-13 11:30 UTC, seluianova commented
> "Worst case" someone can generate a slug for a content objects they shouldn't

This could be eliminated if we check for "cms.change_page_object" permission instead of "is user.role == Observer".
This will also make the check more accurate, because the slug can actually be edited when the user has permissions to a particular page and being an Observer is not enough.
But it will require some re-work of slugify_ajax() function. Not sure it's worth it, given the criticality of the original issue.

2024-05-13 11:58 UTC, seluianova commented on integreat_cms/cms/templates/pages/page_sbs.html
> +                            <button name="status"
Currently we don't have ajax slug generation in the sbs form (probably it's a bug though)

2024-05-13 12:14 UTC, seluianova commented on integreat_cms/cms/templates/pages/page_sbs.html
> +                            <button name="status"
I have created a separate issue for that

2024-05-15 07:51 UTC, charludo commented
> > "Worst case" someone can generate a slug for a content objects they shouldn't
> 
> This could be eliminated if we check for "cms.change_page_object" permission instead of "is user.role == Observer". This will also make the check more accurate, because the slug can actually be edited when the user has permissions to a particular page and being an Observer is not enough. But it will require some re-work of slugify_ajax() function. Not sure it's worth it, given the criticality of the original issue.
> 
> Smthg like:
> 
> ```
> request.user.has_perm("cms.change_page_object", object_instance.page)
> ```
> 
> But I don't insist here, let me know if you would prefer to keep the current implementation.

You're absolutely right, that makes a lot more sense. Tbh I completely forgot that checking permissions for a specific object is an option... 😅

2024-05-24 08:19 UTC, charludo commented on integreat_cms/cms/views/utils/slugify_ajax.py
> +    ):
Oh no, I think I forgot to complete the refactor 🙈 That's a bit embarassing.

2024-05-24 08:19 UTC, charludo commented on integreat_cms/cms/templates/imprint/imprint_form.html
> +                                   data-slugify-url="{% url 'slugify_ajax' region_slug=request.region.slug language_slug=language.slug model_type='page' %}"
I guess so!

2024-06-19 14:20 UTC, seluianova commented on integreat_cms/cms/templates/events/event_form.html
> +                                   data-slugify-url="{% url 'slugify_ajax' region_slug=request.region.slug language_slug=language.slug model_type='event' %}"
'if' was necessary for the case where a new event is created.
there is a failure without if

2024-06-19 14:21 UTC, seluianova commented on integreat_cms/cms/templates/pages/page_form.html
> +                                   data-slugify-url="{% url 'slugify_ajax' region_slug=request.region.slug language_slug=language.slug model_type='page' %}"
please return the if condition :)

2024-06-19 14:22 UTC, seluianova commented on integreat_cms/cms/templates/pois/poi_form.html
> +                                       data-slugify-url="{% url 'slugify_ajax' region_slug=request.region.slug language_slug=language.slug model_type='poi' %}"
same here

2024-06-19 15:27 UTC, seluianova approved these changes
I've re-tested everything again and found no new problems except the one caused by removing the if-condition in the templates.
As soon as the if-s are returned, I think it's good to go 🤞
Thanks for tackling this tricky issue!

2024-06-25 07:11 UTC, charludo commented
> I've re-tested everything again and found no new problems except the one caused by removing the if-condition in the templates. As soon as the if-s are returned, I think it's good to go 🤞 Thanks for tackling this tricky issue!

No, thank YOU for the thorough reviews and attention to detail!!

Seriously, without you, this PR *might* have solved the original issue, but would also have introduced multiple new bugs. Thank you 💛

2024-06-25 07:19 UTC, merged