Refactor page permission actions
digitalfabrik/integreat-cms pull request #2655
Opened 2024-02-12 13:35 UTC by ztefanie

### Short description
Refactored the `page_actions.py`

### Proposed changes
- Move page permission actions to separate file
- Introduce `AbstractPagePermission` class, to implement template method pattern to avoid code duplication 
- Split up big functions in smaller functions to increase readability of the code

### Background:
I did some code analysis of our code (integreat-app, integreat-cms and entitlementcard). One result was that the page_actions.py is both a hotspot (=changed frequently) and has one of the lowest code health in our whole codebase. Therefore I created this PR to improve the code quality of this file.

I will show some insights about the code analysis i made in a barcamp at the conference.

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2024-02-13 10:41 UTC, MizukiTemma approved these changes
Cool improvement 😸

2024-03-20 10:04 UTC, JoeyStk requested changes
Thank you very much for your efforts! This is a great contribution!
I only have a few minor (and admittedly nit-picky) comments :)

2024-03-21 09:02 UTC, JoeyStk approved these changes

2024-03-27 09:29 UTC, ztefanie commented on integreat_cms/locale/de/LC_MESSAGES/django.po
> +msgstr "Information: \"{}\" hat diese Berechtigung bereits"
You are right, added the dot.

2024-03-27 09:29 UTC, ztefanie commented on integreat_cms/cms/views/pages/page_permission_actions.py
> +    print(permission_message.level_tag.value)
removed it.

2024-03-27 09:29 UTC, merged