Keep GitHub Actions up to date with GitHub's Dependabot
digitalfabrik/integreat-cms pull request #2676
Opened 2024-02-29 13:15 UTC by cclauss

This will autogenerate pull requests like dataloop-ai/components#890 to fix the warnings like at the bottom right of
https://github.com/digitalfabrik/integreat-cms/actions/runs/8095191243
* https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
* https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem

2024-03-01 14:37 UTC, charludo requested changes
Thank you for your contribution! 🎉 
Please [squash your commits](https://digitalfabrik.github.io/integreat-cms/git-flow.html#clean-up-git-history), and then this looks ready to be merged.

2024-03-01 17:11 UTC, timobrembeck approved these changes
Thanks! :+1:

2024-03-02 09:16 UTC, charludo approved these changes

2024-03-02 10:40 UTC, merged

2024-03-02 10:43 UTC, cclauss commented
Generated:
* #2683