Circleci runs pre commit remove duplicate tests
digitalfabrik/integreat-cms pull request #2742
Opened 2024-04-10 06:26 UTC by cclauss

* #2741 but removing duplicate tests that are already being run by `pre-commit`

2024-04-14 21:32 UTC, timobrembeck reviewed
Thanks a lot, yes this makes sense! :+1:

I already had a similar change in mind, also because it was cumbersome to keep the version definitions in the pre-commit config in sync with the rest of the project. Maybe we can even get rid of these dependencies in the pyproject.toml now? Since pre-commit installs them separately? We would just also have to remove all the dev tools that depend on them. But since pre-commit can also run single checks, I don't see an important reason to keep them.

I had concerns about the run time of the checks, since we loose the ability to run the checks in parallel, but according to CircleCI, it doesn't make a huge difference. Maybe due to the higher resource class, but I guess we can afford it.

Sorry about the new conflicts with the ruff tool, do you think you could resolve them?
In any case, I'm very grateful for all your contributions! :pray:

2024-04-14 22:03 UTC, cclauss commented
The lack of a performance delta might be less about the large memory size and more about avoiding cloning the repo over and over again.

> Maybe we can even get rid of these dependencies in the pyproject.toml now? Since pre-commit installs them separately?

Yes. Yes.

2024-04-29 08:54 UTC, cclauss commented
Given how long it takes to get pull requests reviewed and merged, I hesitate to add more complexity here.
@PeterNerlich

2024-04-29 08:58 UTC, charludo commented
> Given how long it takes to get pull requests reviewed and merged, I hesitate to add more complexity here. Small moves. @PeterNerlich

Yes, sorry, that was more of a general remark regarding the idea of removing the devtools :)

2024-04-29 09:06 UTC, PeterNerlich commented
> Given how long it takes to get pull requests reviewed and merged, I hesitate to add more complexity here. Small moves. @PeterNerlich

> Yes, sorry, that was more of a general remark regarding the idea of removing the devtools :)

Sure, let's keep this idea in mind for a future PR.

2024-06-05 12:57 UTC, deen13 requested changes
Thanks for the pull request! I really like the idea of running all pre-commits in circle ci. ☺️

2024-06-05 13:31 UTC, cclauss commented on .circleci/config.yml
> +    resource_class: large
I believe that it was MyPy that required the extra memory.  Try moving that to a separate job and removing it from pre-commit and dropping back to a small instance.  Much is written about why running MyPy in pre-commit is bad.

2024-06-17 21:11 UTC, closed without merging