Allow dynamic export of database objects
digitalfabrik/integreat-cms pull request #2766
Opened 2024-04-29 14:19 UTC by david-venhoff

### Short description

This is an experimental pr which adds a new api endopint that creates a data export which can be imported using `./tools/integreat-cms-cli loaddata path/to/json`

To preserve user privacy, only whitelisted models get exported and user account information will not be included in the export. Also only administrators are allowed to use this endpoint. 

This is currently a proof of concept and only exports regions, languages, pages and page translations

Please take a look at this and let me know whether this approach is something that could be incorporated :)

### Proposed changes

- Add a `dump` function that exports all objects of selected models as json.
- Add a new api endpoint `/v3/database` which uses this function to create a data export.

### Resolved issues

Fixes: #2516

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2024-05-07 08:59 UTC, ulliholtgrave requested changes
Nice idea and so far it works as expected. However, I have 2 questions:
1. I did test it with our default test data and it was sufficiently fast, but did you do some performance bench marking for a  bigger database?
2. We generally want to use this file as an import for our local setups, right?

2024-05-07 08:59 UTC, ulliholtgrave commented on integreat_cms/locale/de/LC_MESSAGES/django.po
> +msgid "Data dump"
I guess I prefer the term "Database dump" and "Datenbank-Export" in German.

2024-05-07 11:12 UTC, david-venhoff commented
> I did test it with our default test data and it was sufficiently fast, but did you do some performance bench marking for a bigger database?

No, I did not test it with a bigger database. I do expect it to be quite slow however, since we have so many page translations on the production database and a for-loop that has to go over every single one of them. Not sure if there is a way to make it faster.
I would argue that it should be fine however, since this operation should usually only needed once every few months per developer probably.

> We generally want to use this file as an import for our local setups, right?

Probably only for performance testing, unless we can optimize the cms enough that working with realistic test data is bearable.

2024-05-25 09:48 UTC, ulliholtgrave approved these changes
Thank! I was able to export a dataset and import it :+1: 
I guess we still have to think about how and in which form we want to make them available to our devs, but this is a good start

2024-05-25 13:17 UTC, closed without merging

2024-05-25 13:21 UTC, david-venhoff commented
We decided to close this, because it is also possible to use database dumps, and the advantage of this approach is not really big enough to justify it