Fix test discovery in vscode
digitalfabrik/integreat-cms pull request #2788
Opened 2024-05-07 14:28 UTC by deen13

### Short description

This pull request addresses the test configuration and discovery issues in VSCode while eliminating the need for the workaround involving tasks.

### Proposed changes
- Add environment variables that are required for test execution to devcontainer.json
- Eliminate the test tasks, as they were employed solely as a workaround
- Enable pytest in devcontainers
- Update README.md

### Side effects
- Happier devs 🤗 

### Screenshot
![Screenshot 2024-05-07 at 16 21 03](https://github.com/digitalfabrik/integreat-cms/assets/13850172/466ecdd4-67f6-4e33-963b-f6b0ad278d1d)

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2024-05-07 15:08 UTC, charludo requested changes

2024-05-07 15:08 UTC, charludo commented on .env
Hm, I'm not sure I like the introduction of this file. Including only this subset of configuration options is rather inconsistent, while including all configuration options could hinder existing workflows. I'd actually much rather add `.env` to the `.gitignore` and add these values to the setup instructions.

It's also generally discouraged to track `.env` files in git.

2024-05-07 15:08 UTC, charludo commented on .env
Alternatively, could you instead [set these values through the devcontainer `Dockerfile`](https://stackoverflow.com/a/69520132)?

2024-05-08 10:59 UTC, deen13 commented on .env
Good idea! I moved the environment variables to the [remoteEnv](https://containers.dev/implementors/json_reference/) field of [devcontainer.json](https://github.com/digitalfabrik/integreat-cms/blob/fix/vscode-test-discovery/.devcontainer/devcontainer.json).

2024-06-03 13:38 UTC, david-venhoff approved these changes
Thanks!

As we discussed, adding the default interpreter path could be helpful, but that can also be done in another pr :)

2024-06-03 13:58 UTC, merged