Fix upload file behavior on set icon form
digitalfabrik/integreat-cms pull request #2816
Opened 2024-05-28 15:41 UTC by lunars97

### Short description

Currently the upload form on icon set on the editor form of pages does not correctly validate the accepted uploaded files. If the unaccepted file is uploaded, it is removed after 5 seconds. The expected behaviour is that it shouldn't be removed from the upload input and should show type error on mouse over.

### Proposed changes

- Create an object called mediaTypes with a key "allowedMediaTypes" and set the type "any" to it (it was undefined when it was set to string and seems like directly assigning it in a component resulted in an undefined property value)
- Fix importing of mediaTypes in other files and components
- File types filter on file select can be left as it is because based on the browser it behaves differently (Firefox shows now filters with accepted types, Chrome only shows filters like Customised files and all files)

### Side effects

- should be none

### Resolved issues

Fixes: #2623 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2024-06-03 09:29 UTC, deen13 requested changes
Thanks for the fix @lunars97! I tested the issue on my machine and my file picker did not allow me to choose svg files. 👍

In terms of code, I believe we should avoid having any types in our codebase. I've added type definitions on [this branch](https://chatgpt.com/c/0ca75cc1fcf539a85d813fb93b401e3210b58fc8). Feel free to merge it or let me know if anything doesn't work.

2024-06-03 15:47 UTC, lunars97 commented
> Thanks for the fix @lunars97! I tested the issue on my machine and my file picker did not allow me to choose svg files. 👍
> 
> In terms of code, I believe we should avoid having any types in our codebase. I've added type definitions in [this commit](https://github.com/digitalfabrik/integreat-cms/commit/0ca75cc1fcf539a85d813fb93b401e3210b58fc8). Feel free to merge it or let me know if anything doesn't work.

thank you for your review! :) Upload choices constant does not include SVG file, it only contains jpeg and png file as well as pdf as a document file. I will have a look at your commit, thank you :)

2024-06-03 21:41 UTC, deen13 commented
> > Thanks for the fix @lunars97! I tested the issue on my machine and my file picker did not allow me to choose svg files. 👍
> 
> > 
> 
> > In terms of code, I believe we should avoid having any types in our codebase. I've added type definitions in [this commit](https://github.com/digitalfabrik/integreat-cms/commit/0ca75cc1fcf539a85d813fb93b401e3210b58fc8). Feel free to merge it or let me know if anything doesn't work.
> 
> 
> 
> thank you for your review! :) Upload choices constant does not include SVG file, it only contains jpeg and png file as well as pdf as a document file. I will have a look at your commit, thank you :)

Oh yeah, I meant that as a confirmation that it works on my machine. 🙈😄

2024-06-06 17:23 UTC, lunars97 commented
> > > Thanks for the fix @lunars97! I tested the issue on my machine and my file picker did not allow me to choose svg files. 👍
> > 
> > 
> > > 
> > 
> > 
> > > In terms of code, I believe we should avoid having any types in our codebase. I've added type definitions in [this commit](https://github.com/digitalfabrik/integreat-cms/commit/0ca75cc1fcf539a85d813fb93b401e3210b58fc8). Feel free to merge it or let me know if anything doesn't work.
> > 
> > 
> > thank you for your review! :) Upload choices constant does not include SVG file, it only contains jpeg and png file as well as pdf as a document file. I will have a look at your commit, thank you :)
> 
> Oh yeah, I meant that as a confirmation that it works on my machine. 🙈😄

haha I've just noticed your thumbs-up :+1: and I checked your commit and it works :) Thank you!

2024-06-07 09:23 UTC, deen13 approved these changes
Great! 🥇

2024-06-07 10:38 UTC, MizukiTemma approved these changes
Nice 😌 

Should we probably add a release note? and don't forget to squash the commits ;)

2024-06-10 09:53 UTC, lunars97 commented
@MizukiTemma or @deen13 could one of you please check the release note? I am not sure whether I articulated it in a correct way :pray:

2024-06-10 11:34 UTC, MizukiTemma commented
"Show only files of allowed data types when uploading a new file in the content icon setting" would probably describe the effect of the change precisely? 🤔

2024-06-14 07:50 UTC, lunars97 commented
> "Show only files of allowed data types when uploading a new file in the content icon setting" would probably describe the effect of the change precisely? 🤔 I'll leave the german translation to @deen13 😅

Maybe sth like this `Anzeige nur von Dateien mit erlaubten Datentypen beim Hochladen einer neuen Datei in der Inhalts-Icon-Einstellung` ? :thinking:

2024-06-14 09:46 UTC, MizukiTemma commented
I would say "Zeige beim Hochladen einer neuen Datei in der Einstellung für das Inhaltssymbol nur Dateien zulässiger Datentypen an"

2024-06-16 13:38 UTC, lunars97 commented
> I would say "Zeige beim Hochladen einer neuen Datei in der Einstellung für das Inhaltssymbol nur Dateien zulässiger Datentypen an"

I changed the word `Inhaltssymbol` into `Inhaltsicon`. I think the word icon should stay the same for German as well.

2024-06-17 10:08 UTC, MizukiTemma commented
@lunars97 Thank you 😸 It's ready to be merged!

2024-06-17 10:11 UTC, merged