Feature/add bulk action to reset currently in translation
digitalfabrik/integreat-cms pull request #2865
Opened 2024-06-19 14:25 UTC by jarlhengstmengel

### Short description
Add bulk action to reset translation status after exporting pages as XLIFF but rejecting the translation offer.

### Proposed changes

- Add bulk action that only shows when there are pages that are currently in translation
- Bulk action cancels translation process utilizing 'cancel_translation_process_ajax'
- Succes/Error messages are shown for every page that is cancelled

### Side effects

- Since 'cancel_translation_process_ajax' is changed to get Succes/Error Messages, other times this method is used can be affected

### Resolved issues

Fixes: #2007 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2024-06-30 14:50 UTC, JoeyStk reviewed
Thank you very much! To me this looks good already. Do you need some assistance for the tests or do you have an idea how to fix them? :)

2024-07-03 14:50 UTC, jarlhengstmengel commented
Thank you :) Yes I'm a bit struggling to pinpoint where the circular import is happening as the warning from build-documentation says. Maybe you have an idea?

2024-07-05 18:24 UTC, MizukiTemma commented
@jarlhengstmengel 
Could you squash the commits and rebase the branch?

2024-07-17 15:47 UTC, MizukiTemma commented
@jarlhengstmengel 
Sorry for squashing & rebasing, I needed it to fix the problem with build-documentation.

After moving the new view `CancelTranslationProcess` from `bulk_action_views.py` to `page_bulk_actions`, the circular import seems to be resolved 😸 Can we probably publish this PR?

2024-07-17 16:43 UTC, MizukiTemma requested changes
This PR looks already good 😸 There is only one request: can the success/fail messages bundled? Meanwhile messages got bundled so users won't be spammed when they used a bulk action for many pages (see #2606 ).

2024-07-22 13:35 UTC, jarlhengstmengel commented
Thanks @MizukiTemma, I was really stuck on how to resolve the circular import.

2024-08-05 09:31 UTC, JoeyStk requested changes
Thank you very much for your changes! This is almost good to go! :rocket:

2024-08-05 09:31 UTC, JoeyStk commented on integreat_cms/cms/views/pages/page_actions.py
> +        f"Cancelled translation process for page {page} and language {page_translation.language}",
I still see two issues here:

1. This string also appears in English in the German version of the system. I think this should be how to fix it. 

```suggestion
        _("Cancelled translation process for page {page} and language {page_translation.language}"),
```
Then by running `./tools/translate.sh` it should generate a new translation file where you can then insert the German translation for this sentence.

2. The success messages are created in bulk and therefore overpopulating the screen (s. screenshot).
For that we wrote the `iter_to_string` function that puts the list into a string and then just shows that one message. You can find an example of this in use [here](https://github.com/digitalfabrik/integreat-cms/blob/develop/integreat_cms/cms/views/bulk_action_views.py#L179)

![grafik](https://github.com/user-attachments/assets/2e6f5370-15b5-4fe4-98c3-37f3997f4200)

2024-08-19 07:37 UTC, JoeyStk approved these changes
Thank you very much for your changes. I think this is ready to be merged now :)

2024-08-19 07:37 UTC, JoeyStk commented on integreat_cms/cms/views/pages/page_bulk_actions.py
> +        succes = []
```suggestion
        success = []
```
Nit: A small typo - and I'd probably call it `success_messages`, but I can live with `success` too :)

2024-08-19 13:11 UTC, MizukiTemma requested changes
Thank you for updates 💪 It's almost ready to go 🐈‍⬛ 

I have one sugegstion to adjust error/success message to fix the points below:

1. "Successfully cancelled" was shown also for pages that were not in translation process. This might be confusing. So, check whether the page is in translation process before calling the ajax function.
2. Use the bundling style same to bulk archiving etc. Before the message looked like

"Die Seite "Willkommen → Willkommen in Augsburg" hat keine Übersetzung für die Sprache "en"" und "Die Seite "Willkommen → Kontakt zu App Team Augsburg" hat keine Übersetzung für die Sprache "en""

repeating the whole sentence for a single object.

2024-08-19 13:11 UTC, MizukiTemma commented on integreat_cms/cms/views/pages/page_bulk_actions.py
> +        messages.error(request, iter_to_string(error))
```suggestion
        language_slug = kwargs["language_slug"]
        not_in_translation = []
        cancel_successful = []
        cancel_failed = []

        for content_object in self.get_queryset():
            if not content_object.get_translation_state(language_slug) == translation_status.IN_TRANSLATION:
                not_in_translation.append(content_object.best_translation.title)
            else:
                cancelation_response = cancel_translation_process_ajax(
                    request,
                    region_slug=content_object.region,
                    language_slug=language_slug,
                    page_id=content_object.id,
                )
                if cancelation_response.status_code == 200:
                    cancel_successful.append(content_object.best_translation.title)
                if cancelation_response.status_code == 404:
                    cancel_failed.append(content_object.best_translation.title)
        
        if not_in_translation:
            messages.success(
                request,
                ngettext_lazy(
                    "{model_name} {object_names} was not in translation process.",
                    "The following {model_name_plural} were not in translation process: {object_names}",
                    len(not_in_translation),
                ).format(
                    model_name=self.model._meta.verbose_name.title(),
                    model_name_plural=self.model._meta.verbose_name_plural,
                    object_names=iter_to_string(not_in_translation),
                ),
            )
        if cancel_successful:
            messages.success(
                request,
                ngettext_lazy(
                    "Translation process was successfully cancelled for {model_name} {object_names}.",
                    "Translation process was successfully cancelled for the following {model_name_plural}: {object_names}",
                    len(cancel_successful),
                ).format(
                    model_name=self.model._meta.verbose_name.title(),
                    model_name_plural=self.model._meta.verbose_name_plural,
                    object_names=iter_to_string(cancel_successful),
                ),
            )

        if cancel_failed:
            messages.error(
                request,
                ngettext_lazy(
                    "Translation process could not be successfully cancelled for {model_name} {object_names}.",
                    "Translation process could not be successfully cancelled for the following {model_name_plural}: {object_names}",
                    len(cancel_failed),
                ).format(
                    model_name=self.model._meta.verbose_name.title(),
                    model_name_plural=self.model._meta.verbose_name_plural,
                    object_names=iter_to_string(cancel_failed),
                ),
            )
```

2024-08-19 16:11 UTC, jarlhengstmengel commented
I'm a bit lost on how to resolve the fuzzy translations in `django.po`. What is the syntax when using `{}` with `ngettext_lazy`?

2024-08-19 17:47 UTC, MizukiTemma commented
> I'm a bit lost on how to resolve the fuzzy translations in `django.po`. What is the syntax when using `{}` with `ngettext_lazy`?



> I'm a bit lost on how to resolve the fuzzy translations in `django.po`. What is the syntax when using `{}` with `ngettext_lazy`?


[This part](https://github.com/digitalfabrik/integreat-cms/blob/768891a7552fe27adb5d340a26b697d437ae93ff/integreat_cms/locale/de/LC_MESSAGES/django.po#L8631-L8642) probably helps as an example

2024-08-19 20:39 UTC, jarlhengstmengel commented
> > I'm a bit lost on how to resolve the fuzzy translations in `django.po`. What is the syntax when using `{}` with `ngettext_lazy`?
> 
> > I'm a bit lost on how to resolve the fuzzy translations in `django.po`. What is the syntax when using `{}` with `ngettext_lazy`?
> 
> [This part](https://github.com/digitalfabrik/integreat-cms/blob/768891a7552fe27adb5d340a26b697d437ae93ff/integreat_cms/locale/de/LC_MESSAGES/django.po#L8622-L8629) probably helps as an example

Thanks :) now it works

2024-08-20 09:20 UTC, MizukiTemma approved these changes
🚀 Looks good 🎉 

The last step: squash the commits before merging 😉

2024-08-21 08:57 UTC, merged