Add link checker to the `to-do-board`
digitalfabrik/integreat-cms pull request #2889
Opened 2024-07-02 13:16 UTC by JoeyStk

### Short description

This PR adds an AJAX call for the link checker row on our To-Do-Board in order to hopefully increase the loading times so we can enable the row on our system.

### Proposed changes

- Add an AJAX call for the broken link context
- Add additional optional properties to the HTML template

### Side effects

- The loading times were normal for 1200+ pages in one region (but only 7 regions and not a lot of pages in the other regions). Is there a way to test this more reliably before merging it and testing it on the test system? 

### Resolved issues

Fixes: #2824

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2024-07-04 14:25 UTC, david-venhoff commented
> The loading times were normal for 1200+ pages

Unfortunately the performance problems on the production server are caused by the many page translations (mostly old versions)

> Is there a way to test this more reliably before merging it and testing it on the test system?

Yes, you can load a database dump onto the test system to test it with realistic data. We still need to create proper documentation for how to do that, but for now you can take a look here: https://github.com/digitalfabrik/integreat-cms/pull/2832#issuecomment-2182293775
I have shared a dump on the nextcloud with you.

I did some tests with the database dump on this pr, and unfortunately, for münchen it takes over a minute to load on my pc. Maybe it makes sense to wait for #2832?
![image](https://github.com/digitalfabrik/integreat-cms/assets/78504586/3ac555ec-7d4f-4ec5-8a32-70150d4da721)

2024-07-04 19:28 UTC, JoeyStk commented
> Maybe it makes sense to wait for https://github.com/digitalfabrik/integreat-cms/pull/2832

Sure, makes sense :)

2024-07-06 15:46 UTC, JoeyStk commented
@david-venhoff I rebased to develop now. Could you please check, if the loading times have improved? If not, I will talk to @osmers about it :)

2024-07-08 08:28 UTC, deen13 requested changes
I encountered an error during testing after running `./tools/install.sh` and `./tools/run.sh`. Additionally, I expected the frontend to display an error message in this scenario. 😊

```
Jul 08 08:20:50 ERROR django.request - 500 Internal Server Error: /testumgebung/ajax/dashboard/broken-links/
Traceback (most recent call last):
  File "/Users/deen/Coding/integreat-cms/.venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deen/Coding/integreat-cms/.venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deen/Coding/integreat-cms/integreat_cms/api/decorators.py", line 116, in wrap
    return function(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deen/Coding/integreat-cms/integreat_cms/cms/views/dashboard/dashboard_view.py", line 171, in get_broken_links_context
    "url_id": invalid_url.pk,
              ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'pk'
```

2024-07-08 08:28 UTC, deen13 commented on integreat_cms/static/src/js/dashboard/broken-links.ts
> +    return content;
```suggestion
    return await response.json();
```

2024-07-08 08:28 UTC, deen13 commented on integreat_cms/static/src/js/dashboard/broken-links.ts
> +        getContent(url).then((json) => {
To maintain consistency with promise resolution, I would prefer this to be awaited.

2024-07-18 12:42 UTC, JoeyStk commented
@deen13 Thank you for your review. The suggested changes should be implemented now :) Could you please review this PR again? :)

2024-07-23 07:13 UTC, deen13 approved these changes
Works like a charm 😌

2024-07-25 14:04 UTC, MizukiTemma approved these changes
Cool 🎉 Thank you so much 🙏

2024-07-26 13:01 UTC, merged