Show only organization of the region in POI form
digitalfabrik/integreat-cms pull request #2932
Opened 2024-07-25 12:33 UTC by MizukiTemma

### Short description

This PR fixes the bug that ALL organizations were shown as choice in the POI form.

### Proposed changes

- Apply the same procedure with the page form and view

### Side effects

- None? I hope 🙈 

### Resolved issues

Fixes: #2928 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2024-07-26 13:00 UTC, JoeyStk requested changes
Thank you very much for the quick fix! The implementation works well and does what it's supposed to do. I only have a few suggestions on code style. Please find them below :)

2024-07-26 13:47 UTC, MizukiTemma commented on integreat_cms/cms/forms/pois/poi_form.py
> +        # Set choices of organizations manually to filter only organizations of the region of the page
Removed together with an equivalent comments in the page form

2024-07-26 15:31 UTC, JoeyStk approved these changes
Nice, thank you very much! :rocket:

2024-08-01 08:27 UTC, deen13 approved these changes
I tested the feature on my machine and it works. 😌

2024-08-01 11:00 UTC, merged

2024-08-01 11:54 UTC, osmers commented
@MizukiTemma does this also fix the drop down in the organisation selection menu in the user settings? Or would that be a different issue?

2024-08-01 12:38 UTC, MizukiTemma commented
This fixes only the organization drop down in the POI form. I'll open another issu.