Allow MT only when user can publish
digitalfabrik/integreat-cms pull request #2997
Opened 2024-08-14 09:44 UTC by MizukiTemma

### Short description

This PR makes our MT feature available only for users who are allowed to publish the target contents.

### Proposed changes

- Change `is_permitted` to check whether the current user can "publish" the content(s) (required: `can_change` for Event and POI as before, `can_publish` for Page either per role >= Editor or per page based permission or as organization member)
- Deaktivate MT bulk action completely for observers and authors

### Side effects

- `is_permitted`, `DeeplApiClient` and `GoogleTranslateApiClient` are extended with a variable. I hope this won't affect other parts, for it is "optional" with default value
- 

### Resolved issues

Fixes: #2961 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2024-08-15 10:49 UTC, deen13 commented
Hey @MizukiTemma, can you provide a step-by-step guide on how to test this pull request? That'd be great. 🤗

2024-08-15 14:05 UTC, MizukiTemma commented
@deen13 
Thank you for your interest in this confusing PR 😸 

I think it's the best to log in as different roles and see whether MT is available.

-----The wished state-----
Events and locations: if you have permission "change_event"/"change_poi" you can use MT both by bulk action and check box in the form
Pages: if you have permission "publish_page", you can use MT both by bulk action and in the form.

-----The tasty point-----
Observers have neither "change_page" nor "publish_page" and authors have "change_page" but no "publish_page". As they are not allowed to finalize/publish any page, MT should not be available for them.
However, they can be entatiled for "publishing" certain pages if they are lised as editors in the area "Additional permissions for this page" in the form or their organization is assigned as "Responsible organization".
In such special cases, even for those restricted roles, MT should be available in the form. Bulk action MT should be though not available.


Tipp: the "Update" Button on the upper right corner of the form must be accompanied by checkbox for MT.
Only "Submit for approval" is available or no button for upate appears, then MT should not be available.

2024-08-23 12:33 UTC, charludo requested changes
I just spent quite a while trying to understand the purpose of the `content` variable being passed around, but think I finally got it. Unfortunately, I think passing it around just for the purposes of the one check in `is_permitted()` is a bit convoluted and hard to follow 🙈 

What do you think of the following idea:
    - bulk action translations are only allowed for staff users, and since in the call to `mt_provider.is_permitted()`, `content` is *not* handed down, I think it's safe to say this check isn't relevant for bulk actions
    - so how about moving the PageTranslation-specific checks to the `PageTranslationForm` instead?
    
This way `content` can be removed as a parameter again, and I *think* this would be equivalent (and, IMO, a little cleaner).

Do call me out though if this is nonsense 😅 😅

2024-09-02 10:36 UTC, MizukiTemma commented
@charludo Thank you for review, I agree with your idea 👍 That will be a way cleaner solution 😸 

This PR will be closed as its changes must be now reverted.

2024-09-02 10:36 UTC, closed without merging

2024-11-06 08:02 UTC, charludo commented
@MizukiTemma do you want to open a second PR for this, or would you like someone else to work on the issue?