Sort news/push notifications
digitalfabrik/integreat-cms pull request #3164
Opened 2024-10-31 22:02 UTC by PeterNerlich

### Short description

News items are sent out as push notifications to subscribed devices as well as served via our API. Push notifications are saved as separate objects in our database in order to retain the information for which news items we already sent notifications and to keep that separate from the concept of the content of the news item itself.

News items have a property `last_updated`, which describes when the content was last edited. Push Notification objects have a `sent_date`, which describes when the notification for this news item in that channel and this language was sent out. In the API, we only expose `last_updated`, which is the value also being displayed in the app. This can cause confusion whenever the date the news item was last edited is far before the date when it was actually sent.

### Proposed changes

- Add a value `display_date` to each news item returned by the API which equals either `last_updated` or `sent_date` of the corresponding push notification, whichever is greater *(effectively clamping the value of `last_updated` to be no earlier than `sent_date`)*
- Sort the news entries returned by the API by the `display_date` value instead of `last_updated`

> *Alternatively, we could decide to alter `last_updated` or `timestamp` to the new behaviour. It seems that we deprecated `timestamp` in 2022 in favour of the new `last_updated`, but it is still in use by the app. There are hints that converting the timestamp to be in the local time zone of the server is the reason, but we should ask directly if we wish to pursue such an alternative.*

### Side effects

- After this PR is merged and released, the app will need to switch from ~~`last_updated`~~ `timestamp` over to `display_date`. No further change should be required.
  If it aligns with how the app team handles this, https://github.com/digitalfabrik/integreat-app/issues/2952 might be repurposed for that request.

### Resolved issues

Fixes: #2994

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2024-11-04 14:00 UTC, MizukiTemma approved these changes
Looks good 😸

2024-11-04 14:00 UTC, MizukiTemma commented
>After this PR is merged and released, the app will need to switch from last_updated timestamp over to display_date. No further change should be required.
If it aligns with how the app team handles this, https://github.com/digitalfabrik/integreat-app/issues/2952 might be repurposed for that request.

@steffenkleinle FYI

2024-11-04 14:05 UTC, steffenkleinle commented
> > After this PR is merged and released, the app will need to switch from last_updated timestamp over to display_date. No further change should be required.
> > If it aligns with how the app team handles this, [digitalfabrik/integreat-app#2952](https://github.com/digitalfabrik/integreat-app/issues/2952) might be repurposed for that request.
> 
> @steffenkleinle FYI

Thanks for the ping. Could we perhaps adjust the naming to `last_update` to be consistent with all other endpoints? In the end, sending a push notification is also some sort of update to the news item. Otherwise, this looks good as is.

2024-11-05 11:56 UTC, david-venhoff reviewed
Not a review, but I noticed that this change should be documented in our api documentation

2025-01-16 20:44 UTC, JoeyStk requested changes
Thank you very much! 
Could you please still add the documentation as @david-venhoff had pointed out and rename the endpoint as @steffenkleinle had pointed out? That'd be great :)
Other than that I don't have any further requests :)

2025-03-11 16:19 UTC, JoeyStk commented
@PeterNerlich what is the state of this PR? :)

2025-03-31 09:02 UTC, JoeyStk commented
@PeterNerlich quick question: What is the state of this PR? Are you still going to work on it? :)

2025-04-28 12:03 UTC, JoeyStk approved these changes
LGTM :rocket:

2025-04-28 13:19 UTC, merged

2025-04-29 08:51 UTC, steffenkleinle commented
> @steffenkleinle Sorry for the long delay. After procrastinating over adjusting this as you suggested, or adding `display_date` to every endpoint for consistency, or merging it as is for way too long because I didn't really feel comfortable with either option, I asked for the opinion of the team. They saw it fair to just merge it with `display_date` – in the future, we will hopefully implement a proper strategy for versioning our API, and on the next major version `last_update` will probably behave like `display_date` does now. I hope this is an acceptable solution!

Sorry, but I am a little lost here. What does that mean for us? Can you provide a short summary which properties exist now with which behavior and which one we should use for sorting? Or is the sorting done entirely in the CMS already?

2025-04-29 16:22 UTC, PeterNerlich commented
@steffenkleinle Sure thing!

- `last_update` is kept as is for now
- `display_date` is the new field with the intended behaviour of assuming either the date the notification was sent, or when the content was last updated, whichever is newer. This is the value that should be shown in the app from now on
- The CMS is delivering this list pre-sorted, newest `display_date` first. I'm not sure if you want to rely on that or make sure we don't send you bogus data though, you are the representation layer after all
- Other endpoints are not affected