Add contact creation in POI form
digitalfabrik/integreat-cms pull request #3196
Opened 2024-11-11 13:07 UTC by jarlhengstmengel

### Short description

This PR adds the creation of contacts with a collapsible box in the POI form.

### Proposed changes

- Add collapsibele box with a contact form in POI form
- Add view for the box
- Trigger creation of a contact with clicking at publish and setting the location automatically to the POI that is created parallel

### Side effects

- None

### Resolved issues

Fixes: #3088 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2024-11-12 12:49 UTC, MizukiTemma commented on integreat_cms/cms/templates/pois/poi_form.html
> +                    {% if not poi_form.instance.id and perms.cms.change_contact %}
```suggestion
                    {% if poi_form.instance.id and perms.cms.change_contact %}
```
I guess you want to show this box only when an existing POI is being edited, not when a new POI is being created on the POI form.

2024-11-12 12:51 UTC, MizukiTemma commented
The new typescript file "contact_box.ts" needs to be added in "index.ts", otherwise it can't bring its effects 😿

2024-11-13 08:45 UTC, jarlhengstmengel commented
> The new typescript file "contact_box.ts" needs to be added in "index.ts", otherwise it can't bring its effects 😿

Thank you for the hint! That would have been my question.

2025-01-07 16:02 UTC, MizukiTemma commented
@jarlhengstmengel 
I'll join to implementation of this PR ➕

2025-01-09 16:09 UTC, MizukiTemma commented
This PR implements ony the first step ([see this](https://github.com/digitalfabrik/integreat-cms/issues/3088#issuecomment-2488402054))

The second step will be a separate issue (#3322 )

2025-01-10 15:57 UTC, JoeyStk reviewed
Thank you a lot to the both of you! 
This is a really good step forward. I have a few questions, but other than those it looks already very good :)

2025-01-10 15:57 UTC, JoeyStk commented on integreat_cms/locale/de/LC_MESSAGES/django.po
> +msgstr "Ein neuer Kontakt wurde erfolgreich erstellt."
```suggestion
msgstr "Der neue Kontakt wurde erfolgreich erstellt."
```
This is very nit picky, but I think we should keep the definitive article to stay consistent to the English version, but yes, it doesn't sound as good

2025-01-10 15:57 UTC, JoeyStk commented on integreat_cms/static/src/index.ts
> +
```suggestion
```

2025-01-10 15:57 UTC, JoeyStk commented on integreat_cms/cms/templates/pois/poi_form_sidebar/related_contacts_box.html
> +                        <i icon-name="pen-square" class="mr-2"></i> {{ contact.label_in_reference_list }}
```suggestion
                        <i icon-name="pencil" class="mr-2"></i> {{ contact.label_in_reference_list }}
```
At least for the list views we changed the icon to the pencil, but maybe it's okay for this view because the context is slightly different? (And also: we still use this icon still in a few places)

2025-01-13 09:35 UTC, MizukiTemma commented
@JoeyStk 
Thank you for the review 😸 Your suggestion are applied 👍

2025-01-16 16:58 UTC, JoeyStk approved these changes
Thank you very much!

2025-01-17 08:44 UTC, charludo requested changes
THank you, this already looks great! 🎉 

One question: why is the option to create a new contact only shown for existing POIs? IMO it would be very convenient to also be able to create a contact at the same time as the POI.

Additionally, I am a bit confused (and I suspect some users might be too) about the intended purpose of the "related contact" vs the "contact information". I think some clarification, or better yet some unification of the features, is necessary.

For example, could a checkbox be added below the "contact information" box to create a new contact based on that information? Then *locations* would immediately become linkable in pages/events, like @nikolahoff suggested in the last weekly.

Similarly, maybe a checkbox "set as default contact information for this location" could be added in the new ajax form this PR adds, which would then auto-fill the contact information of the POI, if it was not set beforehand?

I know this is somewhat beyond the scope of this PR, I just feel that with the addition of this feature, the POI form with its multiple overlapping ideas of contacts/contact details becomes rather confusing. Maybe @osmers also has an opinion on this? 😅

2025-01-17 08:44 UTC, charludo commented on integreat_cms/cms/views/contacts/contact_form_ajax_view.py
> +        contact_instance = Contact.objects.filter(id=None).first()
This will always be `None`, right? There cannot be an object without an ID.

(I assume this was copied from the `POIAjaxFormView`? I think it is an error there, too)

2025-01-17 08:44 UTC, charludo commented on integreat_cms/static/src/js/contact_box.ts
Could you maybe rename this to something more expressive? 😅

2025-01-17 08:44 UTC, charludo commented on integreat_cms/static/src/js/contact_box.ts
> +};
This is cool, what do you think about extracting this into its own PR and applying it globally? 😃

2025-01-17 08:44 UTC, charludo commented on integreat_cms/static/src/js/contact_box.ts
> +    console.debug(data);
```suggestion
```
same here :D

2025-01-17 09:00 UTC, osmers commented
@charludo I was just gonna mention #3180 and definitely agree with your input on being able to create a contact from the POI form :) I think that might be #3088 ?

2025-01-17 09:10 UTC, MizukiTemma commented
@osmers  #3322 is probably better place to leave comments as it's to be implemented in the next weeks.

2025-01-17 09:28 UTC, charludo commented
> @osmers #3322 is probably better place to leave comments as it's to be implemented in the next weeks.

I think I have not had enough coffee yet -.-
Sorry about the noise about things already solved in this thread...

2025-01-22 15:05 UTC, MizukiTemma commented on integreat_cms/static/src/js/contact_box.ts
uff, any suggestion? 😅

2025-01-22 15:31 UTC, MizukiTemma commented on integreat_cms/cms/views/contacts/contact_form_ajax_view.py
> +        contact_instance = Contact.objects.filter(id=None).first()
You're right 👀 😁 Fixed. The one in `POIAjaxForm` will be fixed as #3359 (as not in the scope of this PR)

2025-01-22 16:15 UTC, MizukiTemma commented
@charludo 
Thank you for review 😸 Could you check again?

2025-01-22 18:47 UTC, charludo approved these changes
Thank you, looks great!

2025-01-22 19:11 UTC, merged