Remove checkbox appearence for roles who do not have edit permission in events and locations
digitalfabrik/integreat-cms pull request #3246
Opened 2024-11-27 12:15 UTC by lunars97

### Short description

Checkboxes on list views for location and events are being shown for observer who has no edit permission. 

### Proposed changes

- Add permission check conditions on these list views

### Side effects

- none

### Resolved issues

Fixes: #3014 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2024-11-27 16:45 UTC, david-venhoff requested changes
Thanks, this looks mostly good to me. 

Unfortunately, the paddings get messed up a little if the bulk action column is not included:
![image](https://github.com/user-attachments/assets/5ee30a11-1144-41a0-9b6a-45b540583107)

2024-11-27 16:45 UTC, david-venhoff commented on integreat_cms/cms/templates/events/event_list.html
> +                    {% endif %}
I think the simplest fix for the padding is to simply include the `<th>` always and only hide its child:
```suggestion
                    <th class="py-3 pl-4 pr-2 min">
                        {% if perms.cms.change_event %}
                            <input form="bulk-action-form" type="checkbox" id="bulk-select-all" />
                        {% endif %}
                    </th>
```

2024-11-27 16:45 UTC, david-venhoff commented on integreat_cms/cms/templates/events/event_list_row.html
> +    {% endif %}
```suggestion
    <td class="py-3 pl-4">
        {% if perms.cms.change_event %}
            <input type="checkbox"
                   name="selected_ids[]"
                   value="{{ event.id }}"
                   form="bulk-action-form"
                   class="bulk-select-item" />
        {% endif %}
    </td>
```

2024-11-27 16:45 UTC, david-venhoff commented on integreat_cms/cms/templates/pois/poi_list.html
> +                    {% endif %}
```suggestion
                     <th class="py-3 pl-4 pr-2 min">
                        {% if perms.cms.change_poi %}
                            <input form="bulk-action-form" type="checkbox" id="bulk-select-all" />
                        {% endif %}
                    </th>
```

2024-11-27 16:45 UTC, david-venhoff commented on integreat_cms/cms/templates/pois/poi_list_row.html
> +    {% endif %}
```suggestion
    <td class="py-3 pl-4 pr-2">
        {% if perms.cms.change_poi %}
            <input type="checkbox"
                   name="selected_ids[]"
                   value="{{ poi.id }}"
                   form="bulk-action-form"
                   class="bulk-select-item" />
        {% endif %}
    </td>
```

2024-11-29 14:15 UTC, david-venhoff approved these changes

2024-12-02 08:37 UTC, MizukiTemma approved these changes
Looks good :+1: 

Can we probably add a release note? :smile_cat:

2024-12-03 12:55 UTC, JoeyStk approved these changes

2024-12-03 12:55 UTC, JoeyStk commented on integreat_cms/release_notes/current/unreleased/3014.yml
> +de: Entferne die Anzeige von Checkboxen für Rollen, die keine Bearbeitungsberechtigung für Veranstaltungen und Orte haben
Looks good :)

2024-12-03 13:17 UTC, merged