Fix event creation without physical location
digitalfabrik/integreat-cms pull request #3247
Opened 2024-11-28 13:13 UTC by MizukiTemma

### Short description

This PR fixes the problem that events cannot be created without POI even if "Event does not have a physical location" is checked.

### Proposed changes

- Clean the POI id before passing the user input values into the form.: the cause was "-1", which is passed as POI id if no POI is selected but causes validation error, resulting in the form is judged as invalid (before reaching `clean` method). 
-  Add a test for this case

### Side effects

- I hope none :see_no_evil: 
- 

### Resolved issues

Fixes: #3223 

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2024-11-29 09:49 UTC, lunars97 approved these changes
Everything looks good and works as expected! Thank you for fixing it :yellow_heart:

2024-11-29 13:03 UTC, david-venhoff requested changes
Thanks, also for the tests!

Looks like the bug is that an element can not be found anymore. I get this console error when I click the "has not location" checkbox: 
![image](https://github.com/user-attachments/assets/495058da-2e6f-42bd-a9de-de2f08e9a7a4)

The commit that introduced this bug is https://github.com/digitalfabrik/integreat-cms/commit/6fb7122bd3ef8d1579692722c2b5a320a389faac

There, the id field for the input was removed, which means that the js code that controls it cannot find it anymore.

The fix is to add this to `_poi_address_container.html` line 7: 
```
id="id_location
```

Then we don't need this extra code on the python side :)

2024-12-11 16:54 UTC, MizukiTemma commented
@david-venhoff 
Ohhhh 🙈 I didn't have to dig so much 😅 

Your suggestion is applied 😸

2024-12-11 18:48 UTC, david-venhoff approved these changes
:tada:

2024-12-11 19:19 UTC, merged