Prevent orphaned contact cards
digitalfabrik/integreat-cms pull request #3282
Opened 2024-12-09 15:08 UTC by charludo

`DRAFT until #3169 is merged`

### Short description

Prevent the deletion of contacts as long as pages/pois/events still referr to it. Note that no list of objects referring to the contact in question is shown in the error message, since we show that list in the contact details anyways.

### Proposed changes

- prevent deletion of contacts in the edit view
- prevent deletion in the bulk action view

### Side effects

- none

### Resolved issues

Fixes: #3260

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2024-12-09 16:13 UTC, MizukiTemma commented
@charludo 
Could you add the same check for archiving too? 😸

2024-12-10 06:25 UTC, charludo commented
> @charludo Could you add the same check for archiving too? 😸

done

2025-01-07 12:32 UTC, MizukiTemma requested changes
Thank you for the PR, the protection functions as expected 😸 

I have some suggestion for improvement:

1. Can we probably add to the tests such cases that archiving/deleting is prevented due to referring contents?
2. It's even more cool if error messages are bundled that appear when contacts cannt be bulk archived/deleted, like the corresponding success messages? 
3. Deactivating the buttons if the contact is protected: you can open an issue for this if you think better to separate.

2025-01-08 15:34 UTC, charludo commented
> 1. Can we probably add to the tests such cases that archiving/deleting is prevented due to referring contents?

Absolutely!
But more importantly: I had not realized how much preparation you had already made for this - thank you so much! It was a breeze to add the tests thanks to you!! 💛 
 
> 2. It's even more cool if error messages are bundled that appear when contacts cannt be bulk archived/deleted, like the corresponding success messages?

Done!
 
> 3. Deactivating the buttons if the contact is protected: you can open an issue for this if you think better to separate.

Done!

2025-01-13 09:46 UTC, MizukiTemma approved these changes
Thank you 😸

2025-01-16 21:23 UTC, JoeyStk commented
While testing this I noticed, that the section "The contact is being used on..." doesn't seem to work (right). The test contact card on the page "Important contacts" doesn't show up for test contact 
![grafik](https://github.com/user-attachments/assets/b0f77720-e46a-44d8-83f7-96270dfddcc8)

2025-01-16 21:43 UTC, JoeyStk approved these changes
Thank you very much! 
This looks really good :rocket:

2025-01-17 07:32 UTC, merged