Change error message for external calendars
digitalfabrik/integreat-cms pull request #3307
Opened 2024-12-22 11:25 UTC by JoeyStk

### Short description

This PR changes the error message for importing external calendars to be more speaking

### Proposed changes

- Add new integer field to the model to keep track how many errors there are
- Adjust the error message itself

### Side effects

This PR was worked on with @KateGithub12.

- We don't feel one hundred percent sure about adding the new field to the model, but couldn't think of anything else. Please let us know, if you can see an alternative :)

### Resolved issues

Fixes: #3219

__________________________________________________

[Pull Request Review Guidelines](https://digitalfabrik.github.io/integreat-cms/pull-request-review-guide.html)

2024-12-23 12:47 UTC, MizukiTemma requested changes
Thank you for the PR 😸 

I have some suggestions including an idea to avoid adding the new field to the model.

2024-12-28 15:33 UTC, JoeyStk commented on integreat_cms/cms/views/external_calendars/external_calendar_form_view.py
> +            number_of_errors = external_calendar_instance.number_of_errors
Thank you for your idea. I thought about this option too, but thought this way was less clean than to do it via the model. But I think ultimately there are pros and cons for either way.  What do you think?

I think the cleanest way would probably to create a new model which stores the ImportResult, which could either be an error or a success and which documents the kind of error/success. But I don't know if it's worth the effort

2024-12-28 15:34 UTC, JoeyStk commented on integreat_cms/cms/views/external_calendars/external_calendar_form_view.py
> +            number_of_successes = external_calendar_instance.events.count()
Oh, good catch!

2025-01-02 13:45 UTC, MizukiTemma commented on integreat_cms/cms/views/external_calendars/external_calendar_form_view.py
> +            number_of_errors = external_calendar_instance.number_of_errors
Hmm 🤔 I'm actually for abusing the function return if we stay in the current design/implementation, but the new field has an advantage that we can, for example, show the number of failed imports (or whether all the events of the calendar were successfully imported) in the external calendar list. Yes, both has pros and cons 😅 Let's hear the second reviewer 😸

2025-01-02 14:54 UTC, david-venhoff commented on integreat_cms/cms/views/external_calendars/external_calendar_form_view.py
> +            number_of_errors = external_calendar_instance.number_of_errors
IMHO returning a result from the import function is not unclean at all (And also pretty common practice afaik). If you are worried about returning a tuple, we could instead define a `ImportResult` class or something like that.

If we need the number of errors later, we can change the type of the `errors` field from `CharField` into [`ArrayField`](https://docs.djangoproject.com/en/5.1/ref/contrib/postgres/fields/#arrayfield) (Or alternatively JsonField if we want something non-database specific, but I think that is not important, because we already rely on postgresql in other places)

2025-01-03 14:34 UTC, JoeyStk commented on integreat_cms/cms/views/external_calendars/external_calendar_form_view.py
> +            number_of_errors = external_calendar_instance.number_of_errors
Alright. I'll adjust the function then :)

2025-01-06 10:08 UTC, MizukiTemma approved these changes
Looks good 👍

2025-01-07 11:25 UTC, david-venhoff approved these changes

2025-01-07 11:25 UTC, david-venhoff commented on integreat_cms/cms/utils/external_calendar_utils.py
> +def import_events(calendar: ExternalCalendar, logger: logging.Logger) -> ImportResult:
Github won't let me make a suggestions, but the docstring should be adjusted to mention that this function now returns something

2025-01-07 11:25 UTC, david-venhoff commented on integreat_cms/cms/utils/external_calendar_utils.py
> +
```suggestion
@dataclasses.dataclass(frozen=True, kw_only=True)
class ImportResult:
    """
    Datatype for the result of `import_event`
    """
    number_of_errors: int
```

This is very much a nitpick so feel free to ignore, but this is an ideal candidate for [dataclasses](https://docs.python.org/3/library/dataclasses.html). It would also get rid of the pylint warning.

2025-01-07 11:25 UTC, david-venhoff commented on integreat_cms/cms/views/external_calendars/external_calendar_form_view.py
> +            number_of_successes = 0
```suggestion
```

Isn't this code unreachable, because the external calendar was previously already used in `import_events`?

2025-01-07 11:50 UTC, JoeyStk commented on integreat_cms/cms/views/external_calendars/external_calendar_form_view.py
> +            number_of_successes = 0
Oh yes, you're right. This is still a leftover of the previous version. I will remove it :)

2025-01-07 13:06 UTC, merged

2025-01-13 13:56 UTC, JoeyStk commented on integreat_cms/cms/utils/external_calendar_utils.py
> +    return ImportResult(number_of_errors=len(errors))
Oh! I'm sorry! I will re-add it!